### ISSUE TITLE
how to recognize obsolete classes in NCIT

### ISSUE THREAD

**Issue by marwa811** [owlcs/owlapi#1029]
Iam working with BioPortal ontologies where sometimes I found classes that are obsolete .. If I found any of them I don't want to consider them.. my question how can my code recognize them in OWL API?  In other words, if I have an OWLClass how to check if it is obsolete or not? which function to use?

**Comment by rwynne** [comment]
One way would be to employ a reasoner to collect all children of the 'Retired Concept' class, C28428. This branch should contain all of the "obsolete" classes.

The reasoner method to get subclasses accepts two parameters, the focus class and a boolean. Use true for direct children, or false for all.

`Set<OWLClass> retiredConcepts = reasoner.subClasses(clz, false).collect(Collectors.toSet());`

Another way might be to ignore classes with construct owl:deprecated with value true. I don't know how this is done with the API.
Last, IIRC all Retired classes in NCIT should have annotation Concept_Status = named class Retired_Concept.

**Comment by rwynne** [comment]
_Preface_: There are many ontologies in BioPortal and not all ontologies express obsolete classes the same way.

The subject of this issue is the NCIT and in NCIT the meaning of Obsolete_Concept should not to be confused with Retired_Concept. The NCI EVS staff are the experts and could provide you input on what obsolete means to your use case. Please reach out to them with any questions: NCIThesaurus@nih.gov.

The following method specific to NCIT, with OWL API functions from version 4.1.4, should return true if the given OWLClass has an AnnotationProperty Concept_Status with value Obsolete_Concept:

```
private boolean isObsolete(OWLClass c) {
	for (OWLAnnotationAssertionAxiom anno : EntitySearcher.getAnnotationAssertionAxioms(c, this.ontology)) {
		if (anno.getProperty().getIRI().equals("http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P310") //the IRI for AnnotationProperty Concept_Status
			&& anno.getValue().toString().contains("Obsolete_Concept")) { //a valid filler value for the annotation based on Concept-Status-enum
				return true;
		}
	}
	return false;
}
```

**Comment by marwa811** [comment]
Thanks will try this.
