### ISSUE TITLE
Question: Is the Manchester Syntax antlr file still around?

### ISSUE THREAD

**Issue by bigerl** [owlcs/owlapi#1068]
I am looking for an antlr (at best v4) grammar for Manchester syntax. 

I came across the this veeery old [comment](https://github.com/owlcs/owlapi/blob/28633d2673d558c86b606456a9a303daf6c09311/parsers/src/main/java/org/semanticweb/owlapi/manchestersyntax/parser/ManchesterOWLSyntaxParserImpl.java#L237) that says that once upon a time antlr was used in owlapi. So I was wondering if the respective grammar still exists somewhere. This repo seems not to go back far enough. So it is probably something owlapi v<3?

I am very happy about any hint. Thx in advance. :)

**Comment by ignazio1977** [comment]
This repository contains the same files as the original SVN repository on SourceForge, you can check the branches for older releases, but as far as I'm aware antlr files haven't been part of the build since before 2009.

Maven central contains all releases of owlapi ever made, and it always includes the source - might be worth checking, depending on what you need the grammar for. Note that there have been many bug fixes and even grammar extensions since then, so such old sources would not be equivalent to the current implementation.
