### ISSUE TITLE
[question] what are possible use-cases of `ConcurrentOWLOntologyImpl` ?

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#1110]
Is it important for OWLAPI ?
Which applications use this functionality?

see also https://github.com/owlcs/ont-api/issues/51

**Comment by ignazio1977** [comment]
ConcurrentOWLOntologyImpl is used when an ontology is accessed by multiple threads, some of which might be making changes to the ontology. (If all threads only read form the ontology, then there's no need to use locks).

Not sure which apps are currently relying on it. There was one such app when the functionality was introduced.

**Comment by sszuev** [comment]
> ConcurrentOWLOntologyImpl is used when an ontology is accessed by multiple threads, some of which might be making changes to the ontology. (If all threads only read form the ontology, then there's no need to use locks).
> 
> Not sure which apps are currently relying on it. There was one such app when the functionality was introduced.

Protege with awt\swing events in Event Dispatch Thread?

**Comment by ignazio1977** [comment]
No it was an app being developed for an academic/commercial partnership. Details are a bit fuzzy as this was approximately 2010, we kept getting concurrent modification exceptions and hashmaps stuck because of add operations happening during get operations.

I think there was a second use case, where locking was required to allow imported ontologies to show as loaded while their imports closure was being loaded, but I can't recall enough details.

There's also the fact that many axiom indexes are lazily built and expensive, meaning that avoiding duplicate work is important, but I don't think the locks as implemented make a difference.
