### ISSUE TITLE
Clarify "Entity not properly recognized"

### ISSUE THREAD

**Issue by tobiaswjohn** [owlcs/owlapi#1152]
The following turtle file is an example, where the RDF graph can not properly be parsed to OWL and hence a warning is output by the logger. 
```
<iri>  a _:blank.
```
The warning is the following:
```
org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer getErrorEntity
SEVERE: Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error1 for type Class
```

I think this warning is a bit unspecific, i.e. it would be helpful to include some more information, e.g. whether the problem is parsing a blank node or parsing some data range (those two cases seem to be the only one triggering the message). 

This problem is already mentioned as an [issue for Protege](https://github.com/protegeproject/protege/issues/860), so I think there is some demand to get more information.

**Comment by ignazio1977** [comment]
Yes the problem is that there's a blank node in a place where a class/class expression is expected but there isn't enough information to build it (e.g., no type or onProperty, depending).

In this case there's no information whatsoever, so the only improvement that can be made is to the message wording. If there was some triple associated, it could also be shown. Perhaps something like "class expression incomplete got [triples] but [list of necessary properties] are not available."

**Comment by tobiaswjohn** [comment]
Yes, I think making the message more specific would be helpful. 
For me, adding a comment like "Could not build class for blank node." would already improve the message as it was not clear to me at first, that this is the issue.

**Comment by ignazio1977** [comment]
Added to owlapi 4, 5 and 6
