### ISSUE TITLE
Error parsing RDF/Turtle with triple quoted literals - mismatching single and double quotes

### ISSUE THREAD

**Issue by msalvadores** [owlcs/owlapi#287]
A BioPortal user complaint that one of our ontologies failed to load in Protege 5.

I traced down the bug to the following label:

```
<some_term> skos:altLabel """Diadenosine 5',5'''-P1,P4-tetraphosphate phosphorylase"""@en
```

It seems that the OWLAPI is not matching correctly the termination of the literal. It must be taking the triple double quote as start of the literal and takes the triple single quote as the ending the literal .

Removing the single quotes from the literal made Protege 5 to open the ontology just fine.

I do not know what version of the OWLAPI protege 5 uses.

**Comment by tgbugs** [comment]
I am still encountering this issue in 4.1.1. (Though for some reason the footer says 4.1.0, I did build it using maven)

```
@prefix : <http://FIXME.org/resolver/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix FIXME: <http://FIXME.org/resolver/> .
@prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#> .
@prefix obo_annot: <http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#> .
@base <http://www.w3.org/2002/07/owl#> .

[ rdf:type owl:Ontology
] .


#################################################################
#
#    Annotation properties
#
#################################################################


###  http://FIXME.org/resolver/type

FIXME:type rdf:type owl:AnnotationProperty .



###  http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#synonym

obo_annot:synonym rdf:type owl:AnnotationProperty .



###  http://www.geneontology.org/formats/oboInOwl#hasDbXref

oboInOwl:hasDbXref rdf:type owl:AnnotationProperty .



###  http://www.w3.org/2000/01/rdf-schema#subClassOf

rdfs:subClassOf rdf:type owl:AnnotationProperty .



###  http://www.w3.org/2004/02/skos/core#definition

skos:definition rdf:type owl:AnnotationProperty .





#################################################################
#
#    Classes
#
#################################################################


###  http://FIXME.org/resolver/SCR_000001

FIXME:SCR_000001 rdf:type owl:Class ;
                 
                 FIXME:type "Resource" ;
                 
                 obo_annot:synonym "TransGenic Inc." ;
                 
                 oboInOwl:hasDbXref "nlx_152482" ;
                 
                 rdfs:label "TransGenic" ;
                 
                 rdfs:subClassOf "Commercial Organization" ;
                 
                 skos:definition """An Antibody '''
	         supplier""" .




###  Generated by the OWL API (version 4.1.0) https://github.com/owlcs/owlapi

```

creates the following error when I try to load it with owlapi:
```
Parser: org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParser@362d7c76
org.semanticweb.owlapi.rdf.turtle.parser.ParseException: Encountered " <PN_LOCAL> "supplier "" at line 78, column 9.
Was expecting:
    "." ...
```

**Comment by ignazio1977** [comment]
@tgbugs the error points at TurtleOntologyParser, currently the RioTurtle parser should be favorited. Are you specifying TurtleDocumentFormat as the format to parse?

**Comment by tgbugs** [comment]
I specify TurtleDocumentFormat at save time in the code but not at load and parse time. I call `OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new FileDocumentSource(infile));` back to back (from  [here](https://github.com/tgbugs/ttl-convert/blob/master/src/main/java/scicrunch/App.java)) so that may be causing the problem. I was reusing code that I use to ingest owl and convert it to ttl, but if that is ill advised I can write a ttl specific version.

**Comment by ignazio1977** [comment]
At the moment the RioTurtleDocumentFormat sounds like a better choice. That said, there are bugs open against both, so YMMV.

**Comment by ignazio1977** [comment]
I've just tried this with the latest 4.1.4-SNAPSHOT, after the fix for Rio Turtle export, and I see no failures. The automatically recognized format is Rio Turtle. The parsed ontology looks equivalent to the input, as far as I can tell (there's `rdfs:subClassOf` with a string value in your input - not sure what's the origina of that).

4.1.4 is almost mature for release, if yo can update to use it.
Otherwise I'd recommend trying to specify RioTurtleDocumentFormat on parsing:

`manager.loadOntologyFromOntologyDocument(new FileDocumentSource(infile, new RioTurtleDocumentFormat()));`
