### ISSUE TITLE
XMLLiterals should be output as XML, not quoted XML

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#333]
This was posted on the Protege mailing list by Paul Murray:

I'm finding that protege is rewriting XMLLiteral data in a way that is not all that great.

If I create an ontology with this:

```xml
   <nsl:NameGroup rdf:about='http://biodiversity.org.au/nsl.voc.name-group/[unknown]'>
       <dcterms:title>[unknown]</dcterms:title>
       <dcterms:description rdf:parseType='Literal' rdf:dataType='&rdf;XMLLiteral'><div xmlns='http://www.w3.org/1999/xhtml'>
           <h3>[unknown]</h3>
           <p>
               (describe NameGroup "[unknown]")
           </p>
       </div></dcterms:description>
   </nsl:NameGroup>
```
Protege will xml-quote the xml elements. This makes it awkward to edit uless you load it with protege, and means that the xml loses any xml namespaces that it had inherited from the outer elements (although that's not what I am doing here).

I'd prefer that protege save XML as XML rather than as a string for rdf:parseType='Literal'. Unless that's incorrect.

**Comment by ignazio1977** [comment]
We should be mindful of the restrictions placed on the content here http://www.w3.org/TR/2004/REC-rdf-concepts-20040210/#section-XMLLiteral

In particular, if I understand the spec correctly, namespaces coming from the surrounding rdf/XML code are not recognized. We would have round tripping issues through other syntaxes otherwise, as either we would lose them, or we'd have to modify the lexical form to keep the information. But then it's no longer the same literal.
