### ISSUE TITLE
Annotation subproperty/domain/range disappear after save/load cycle (punning enhancement)

### ISSUE THREAD

**Issue by PieterStroobants** [owlcs/owlapi#351]
When I specify the domain/subpropertyof of an annotation property that also exists as a datatype property, this information is correctly written to the owl file, but after reloading it into protégé this information disappears. Consider the following mwe:
```
<?xml version="1.0"?>


<!DOCTYPE rdf:RDF [
    <!ENTITY dcterms "http://purl.org/dc/terms/" >
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY dc "http://purl.org/dc/elements/1.1/" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
]>


<rdf:RDF xmlns="http://www.semanticweb.org//2015/1/untitled#"
     xml:base="http://www.semanticweb.org//2015/1/untitled"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:dcterms="http://purl.org/dc/terms/"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:dc="http://purl.org/dc/elements/1.1/">
    <owl:Ontology rdf:about="http://www.semanticweb.org//2015/1/untitled"/>



    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotation properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://purl.org/dc/elements/1.1/date -->

    <owl:AnnotationProperty rdf:about="&dc;date">
        <rdfs:range rdf:resource="&rdfs;Literal"/>
        <rdfs:domain rdf:resource="&owl;Thing"/>
    </owl:AnnotationProperty>



    <!-- http://purl.org/dc/terms/date -->

    <owl:AnnotationProperty rdf:about="&dcterms;date">
        <rdfs:subPropertyOf rdf:resource="&dc;date"/>
        <rdfs:range rdf:resource="&rdfs;Literal"/>
        <rdfs:domain rdf:resource="&owl;Thing"/>
    </owl:AnnotationProperty>



    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Data properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://purl.org/dc/elements/1.1/date -->

    <owl:DatatypeProperty rdf:about="&dc;date">
        <rdfs:range rdf:resource="&rdfs;Literal"/>
        <rdfs:domain rdf:resource="&owl;Thing"/>
    </owl:DatatypeProperty>



    <!-- http://purl.org/dc/terms/date -->

    <owl:DatatypeProperty rdf:about="&dcterms;date">
        <rdfs:subPropertyOf rdf:resource="&dc;date"/>
        <rdfs:range rdf:resource="&rdfs;Literal"/>
        <rdfs:domain rdf:resource="&owl;Thing"/>
    </owl:DatatypeProperty>
</rdf:RDF>



<!-- Generated by the OWL API (version 3.5.1) http://owlapi.sourceforge.net -->
```

The file is created using Protégé and the issue occurs with the latest development release (5.0-16) and protégé 4.3.
 Ps. When I delete the datatype property, it works as expected.

**Comment by ignazio1977** [comment]
Punning annotation and datatype properties is a violation of OWL 2 profiles and it means this ontology is OWL 2 FULL.
The fact that roundtripping does not work well might depend on the ambiguities coming from the illegal punning. There have been many changes in OWLAPI 4 and 3.5.2 (still in snapshot version) so this might have changed in the latest code - there's a chance it's a genuine bug, though.

**Comment by sesuncedu** [comment]
There can only be one rdf triple for the domain / range, and it will get consumed only once.  The domain or range will go to the the first triple handler that matches. 

Since RDF to OWL is only defined for DL, this is not a bug per se.  There are enhancements that could be made to handle this case of punning, but they are kind of complex:

1. If an IRI is known to be a punned property at the time the domain/range triple is seen, add a  domain/range axiom for each known property type for which the axiom would be legal (i.e. don't at a datatype as a range for an object property).

2. If a type declaration is encountered that creates a property pun,  and there are existing domain/range axioms for another type of property for the IRI, create appropriate axioms if the domain/range would be legal. 

The rdf encoded OWL would still be non-standard; it would just happen to work with OWL.  

A better solution would be to use a different encoding format, such as OWL FSS or Manchester syntax.

**Comment by ignazio1977** [comment]
As Simon pointed out, the issue here is that this is not an OWL 2 DL ontology. Both the possible fixes described above have the problem that, for punning where only one of the punned properties has a specified domain, we'd be adding the domain to both properties - i.e., the reverse of this issue would be happening. To avoid this, we'd have to change the way triples are consumed during parsing, which is quite a large effort.

On the other hand, the functional syntax format offers this feature as it is - I'd recommend to do it this way.
