### ISSUE TITLE
Does the OWL API Support Oasis XML Catalogs?

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#352]
The OWL API provides several IRI mappers to cache ontology documents locally. Do any of them use Oasis XML Catalogs, as Protege does? Even better, is there one to automatically cache read-in ontologies locally and check the original IRI for updates before using the local copy?

From http://stackoverflow.com/questions/28701613/does-the-owl-api-support-oasis-xml-catalogs

**Comment by ansell** [comment]
We could ask whether the Protege project wants to contribute the xmlcatalog component to OWLAPI, otherwise, they have released it as a standalone module already, with an implementation of OWLOntologyIRIMapper:

https://github.com/protegeproject/xmlcatalog/blob/master/src/main/java/org/protege/xmlcatalog/owlapi/XMLCatalogIRIMapper.java

**Comment by ignazio1977** [comment]
I'll report back to the original question, cheers.

**Comment by ignazio1977** [comment]
No need, you've done so already :-)

**Comment by ignazio1977** [comment]
I've had a look at xmlcatalog; as it's already a neatly self contained project and there's quite a bit of work involved in supporting OASIS catalogs, I think it's better for users to add xmlcatalog to their dependencies rather than embedding it in the OWL API.
