### ISSUE TITLE
Remove OWLAPIParsersModule from the list of modules specified in OWLManager

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#390]
OWLManager specifies a list of modules when creating the guice injector.  One of these is OWLAPIParsersModule.  This doesn't do anything - the code is commented out.

**Comment by ignazio1977** [comment]
It's providing Manchester syntax parsers.
I've deleted the commented code.

**Comment by matthewhorridge** [comment]
o.k. shouldn't these parsers also be located as services?

**Comment by ignazio1977** [comment]
That's a bit more complicated because the parser requires constructor arguments as well, so the class to use could be provided via a service but the actual instance still requires Guice injection. Theoretically that could be the case for all parsers, but this is the only one for which this is required, the others have the support infrastructure in the surrounding classes.
