### ISSUE TITLE
Considerations on OWLLiteral internal storage

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#398]
Is compression used for literals?  It doesn't look like it is used anywhere within the OWL API.  Does anyone know of any projects that set the constructor flag in OWLDataFactoryImpl to true?

I'm just wondering whether this code should be cleaned up.

**Comment by ignazio1977** [comment]
We used to, but it might have been lost at some point. On most ontologies, compression doesn't have a lot of effect.

**Comment by sesuncedu** [comment]
> We used to, but it might have been lost at some point. On most
ontologies, compression doesn't have a lot of effect.

This was a side effect of the way that compression was being applied- one
literal at a time.

Most compression algorithms need a bit of a run-up before they start to win
big.  This involves getting the dictionary properly warmed up. Literal
compression, then, needs to be done in blocks. Uncompressed blocks can be
cached.

There is another form of compression that is usually a space win.

Storing character arrays directly in a literal can save 40 bytes or more;
storing byte arrays where codepoints are all less than 255 can cut this in
half.

Note that for smaller strings there is a per-array overhead, as well as an
8 byte alignment cost.

Allocating storage for these strings in blocks can add a huge win for small
strings; the infrastructure needed is similar to that compressed blocks.

With both kinds of blocked storage there may need to be some form of space
reclamation if enough literals are deleted. This can be done using the
usual techniques - free lists, Mark & sweep, compaction, or save and
reload.

Access patterns at a level above the literal may be the core
considerations; protégé may want to access all the characters of all label
annotation properties in sequence, without needing the string.

Some access patterns may be grouped by entity. It may make sense to use
different pools and different patterns of compression depending on
configuration parameters or from usage patterns.

It seems that most reasoners use their own internal representations for
literal values, so that may or may not affect storage design.
It may be that a better storage system, with better support for some of the
common reasoning tasks (equality, comparison, etc) , might encourage the
use of owlapi literals directly (if an owlapi literal constructs a String
value, and a reasoner retains it, the String will exist alongside the
compressed value).
It may also be that changing the declared type for certain apis from String
to character sequence would allow more flexibility

Regardless, using just byte & char arrays directly (no string) is a
measurable win- enough to make the indexing design float to the top.

**Comment by ignazio1977** [comment]
Good pointers, Simon. I'll rename this issue so that we don't lose them.

To answer Matthew's question, OWLLiteralImpl uses compression if the literal is longer than 160 chars. OWLLIteralImplNoCompression is used if the flag on internals is false - which it always is, apparently.
So we could get rid of that machinery. Simon's proposed alternatives are interesting. Would be great to be able to say OWLLIteral.getLiteral() returns a CharSequence instead of a String, as that would allow us to never have to create Strings more expensive than we need them to be, but that is an impressively vastly scoped change, unfortunately. It would be a few hundreds of changes just in Protege code, and I feel a lot more in other projects.
