### ISSUE TITLE
Return types of RemoveAxiom(s) vs. AddAxiom(s)

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#408]
Was there a reason why the return type for AddAxiom was changed but RemoveAxiom wasn't?

**Comment by ignazio1977** [comment]
Mistake I think - which would mean bug, at this point.

**Comment by ignazio1977** [comment]
With reference to #382, addAxioms, removeAxioms and applyChange(s) should operate transactionally - i.e., all changes are applied or none is. So to return ChangeApplied(SUCCESSFULLY, UNSUCCESSFULLY) sounds like a good idea.

**Comment by matthewhorridge** [comment]
> all changes are applied or none is

What counts a change being applied?  I'm just wondering, if my ontology contains SubClassOf(:A :B) and I apply  ADD  SubClassOf(:A :B) and ADD SubClassOf(:B :C), do any changes get applied?

**Comment by ignazio1977** [comment]
I was just wondering about that.
I think the issue is: adding an axiom which is already there, or removing an axiom that's not there, what are these? Trivially applied (tautologies) or inapplicable? Maybe a third value, ChangeApplied.NoOperation?

**Comment by ignazio1977** [comment]
Current implementation would report them as applied, with no test to see if they are no operations. SQL does the same when asking to delete a nonexisting row, but it barfs on a duplicate insert on unique keys. The semantics there is slightly different though.

**Comment by matthewhorridge** [comment]
Yeah.

I think this is why it was originally a list that was returned.   

For the record.  The old, old, OWL API was allowed to rewrite changes, so that the changes that were applied might be more than the changes that were applied (e.g. for making sure everything was declared).

**Comment by ignazio1977** [comment]
If we leave no op as applied, which matches current behavior, we only need to test for no op when reversing a change because of a rollback within the same transaction - to the outside it will always look like a fully unsuccessful set of changes. Needs care to ensure we don't roll back a no op and end up deleting axioms or adding spurious ones, but should not raise very surprising behaviour.

**Comment by matthewhorridge** [comment]
Under what circumstances does a change application fail?  (Currently)

**Comment by ignazio1977** [comment]
I need to check the details. If a listener protests or it's an issue with renaming, i.e., the rename would create a duplicate, are the ones off the top of my head.

**Comment by ignazio1977** [comment]
My mistake on saying currently no operations are considered successful, they're not:

    protected class OWLOntologyChangeFilter implements
        OWLOntologyChangeVisitorEx<ChangeApplied>, Serializable {

        private static final long serialVersionUID = 40000L;

        @Override
        public ChangeApplied visit(@Nonnull RemoveAxiom change) {
            if (ints.removeAxiom(change.getAxiom())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull SetOntologyID change) {
            OWLOntologyID id = change.getNewOntologyID();
            if (!id.equals(ontologyID)) {
                ontologyID = id;
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull AddAxiom change) {
            if (ints.addAxiom(change.getAxiom())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull AddImport change) {
            // TODO change this to be done inside
            if (ints.addImportsDeclaration(change.getImportDeclaration())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull RemoveImport change) {
            if (ints.removeImportsDeclaration(change.getImportDeclaration())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull AddOntologyAnnotation change) {
            if (ints.addOntologyAnnotation(change.getAnnotation())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

        @Override
        public ChangeApplied visit(@Nonnull RemoveOntologyAnnotation change) {
            if (ints.removeOntologyAnnotation(change.getAnnotation())) {
                return SUCCESSFULLY;
            }
            return UNSUCCESSFULLY;
        }

**Comment by ignazio1977** [comment]
Bit worrying this. If we add two sets of axioms to an ontology, with a duplicate between them, the second addition would report that not all changes have been applied. But the ontology contains the union of the two sets, as expected. I find it a bit counterintuitive - an application could consider it a failed merge.

**Comment by ignazio1977** [comment]
For a transaction, I would do the following:

- for all changes, apply and check if they are successful or no operations;
- If there is an unsuccessful change, reverse all successful changes; ignore no ops
- if all changes are no ops, consider the transaction successful


This allows for successful merges, and an unsuccessful addition of a set of axioms will not delete duplicate axioms from the ontology.

Currently no ops are considered failures; the other cases that cause failures are only vetoing listeners and illegal renames. So, basically, once the change visitor in the ontology is reached, there cannot be any failures, bar runtime exceptions. we should probably catch those and try and recover, so that we can roll back the failure properly. I'm afraid sometimes this might not be reliable.

**Comment by ignazio1977** [comment]
The discussion here is more relevant for #382 than for this issue :-)
