### ISSUE TITLE
RDF 1.1 datatype rdf:langString support

### ISSUE THREAD

**Issue by LorenzBuehmann** [owlcs/owlapi#427]
This is probably not an issue, but with RDF 1.1 rdf:langString was introduced as an additional datatype and there is no rdf:plainLiteral anymore. If somebody uses this datatype as range for a data property, OWL API handles this property as object property, probably because this is not a built-in entity yet.

I'm not sure if OWL API should stick to [OWL 2 datatypes](http://www.w3.org/TR/owl2-syntax/#Datatype_Maps) only, but if not it might be worth to add support for rdf:langString .

**Comment by ansell** [comment]
Hi Lorenz,

There is some previous discussion about this in Pull Request #218 , and issues #172 and #174.

Would you mind if we closed this issue and you continue the discussion at one of those locations?

**Comment by sesuncedu** [comment]
Pick an issue,  any issue :)

I think I ran through a list of possible interpretations and translations
in one of them. It's really  a matter of picking which way to roll.

[Also, I hate langString for what it didn't do - it acknowledges that every
literal should have a datatype, and that the subset of PlainLiteral that
maps to langString has to be a tuple,  but it didn't open the door to any
other kind of literals that are n-triples... so arrays and dictionaries
remain syntactic sugar for cons cells and blank nodes...]

**Comment by ansell** [comment]
Yes yes, I wasn't implying that we had centralised discussion of it so far, but keeping the discussion moving will help and Lorenz has expressed an interest in the discussion.

Many RDF theorists actually hate the concept of unique language literals because they move away from simple value+datatype combinations. Ie, they would prefer if the datatype was the sole denominator, and the language tag was concatenated with the literal value to make a typical datatyped literal. 

Ie, instead of "G'day"@en-au with the (invisible to most concrete syntaxes) datatype rdf:langString, it could be  "G'day@en-au"^^rdf:langString (with a datatype that is always in the concrete syntax), which is exactly the same structure as every other literal and therefore doesn't need a theoretical basis, just a datatype processing tool to split the language tag out before visualising the literal value.

However, there is probably no going back from the way language tagged literals are done right now, so that is probably just a dream.

**Comment by LorenzBuehmann** [comment]
Ah sorry, I missed the related issues. Sure, we can close this issue here and refer to the other related ones.
