### ISSUE TITLE
rdf:list items are lost when ontology is saved

### ISSUE THREAD

**Issue by Mulder8472** [owlcs/owlapi#437]
## Description
When loading an ontology which contains rdf:list items and the writing the ontology to a file, the resulting file is missing the list items but instead an empty anonymous block is generated.

## Versions
I observed this behaviour with version4.0.2 as well as 4.1.0-RC2

## Example:

Before | After
--- | ---
`<http://foo.com> sh:shapes (<http://foo.com>  <http://bar.com> ) .` | `<http://foo.com> sh:shapes [ ] .`

### Complete input file:
`@prefix sh: <http://www.w3.org/ns/shacl#> .
<http://www.foo.com> sh:shapes (<http://www.foo.com>  <http://www.bar.com> ) .`

### Code to reproduce:
```java
    public static void main(String[] args) throws Exception
    {
	String taxonomyFile = "PATH TO SAMPLE FILE HERE";
	OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
	OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new FileDocumentSource(new File(taxonomyFile)));
	OWLDocumentFormat format = manager.getOntologyFormat(ontology);
	TurtleDocumentFormat ttlFormat = new TurtleDocumentFormat();
	if (format.isPrefixOWLOntologyFormat())
	{
	    ttlFormat.copyPrefixesFrom(format.asPrefixOWLOntologyFormat());
	}
	manager.saveOntology(ontology, ttlFormat, System.out);
    }
```

**Comment by ignazio1977** [comment]
Thanks for the example. This looks plain RDF rather than an actual ontology, but still the behaviour looks wrong, and should be possible to do better.

**Comment by ignazio1977** [comment]
The problem here is that the Turtle parser cannot find a matching axiom handler for this input construct - this is valid RDF, but the closest OWL construct is an annotation assertion axiom. The value for such an assertion is not allowed to be a list, but must be a single node. So, the the blank node representing the start of the list is taken to be the value of the annotation, and the rest of the list contents is lost.

As this is not a valid OWL input, it is difficult to figure out the best way forward. Even enhancing the parser and the renderer to allow these structures to be parsed, there is no exact representation in the OWLAPI object model.

Can you describe the use case for this input?

**Comment by sesuncedu** [comment]
AnnotationValue can be an anonymous individual, but- I can't remember if
the rdf List and associated properties are allowed in OWL DL,  as they are
in the reserved vocabulary, and the car can be a literal or an individual.

Each cons cell in the list is going to require a new anonymous individual,
and a couple of assertions. Basically straight mapping the triples into
assertions (not strictly legit,  but seems straightforward enough (for
hacks in the rdf mapping code).

**Comment by ignazio1977** [comment]
But once they've been turned in annotation assertions between the blank nodes building the list, on rendering to Turtle they'd show as separate annotation assertion axioms rather than nicely merged in a list. Would require some hacking of the renderer as well, and same for other formats - otherwise we'd not be able to translate from one format to another and back. Mmm.

**Comment by Mulder8472** [comment]
The example above is just one I constructed for demo purposes ;)

We (the semantics guys) use a tool that executes above code snippet to sort our RDF Turtle files. The tool they use (Protege) does not keep the same order, so before they commit their changes to GIT, they run a normalization process. Keeping the ordering allows the GIT diff viewer to show something meaningful, i.e. if you don't run the tool, it looks like the whole file has changed but with proper ordering maintained, it is easy to identify changes in the diff viewer. This becomes a real pain in case of a merge conflict and you would have to manually merge the files.

**Comment by ignazio1977** [comment]
Ah right, I see.
In 4.1.0 we have better reliability of output order (thanks to @sesuncedu, mostly), so as long as the order you want is alphabetical on the iris (abbreviated if any prefix is defined) you should get the behavior out of the box. Protégé is updating to this new version, so in the medium to long term you should see improvements. Longer term we'll make the ordering strategy easier to manage.

**Comment by sesuncedu** [comment]
I wrote some simple code that took a bunch of pathnames on the command line, read each one in, then wrote it out using the new output code. I could dig this out, but it's almost as easy just to use the code you have in the snippet, but run it on the protege output without doing any RDF wrangling first.  

[I have not run any statistics comparing git diffs for text/turtle formatted OWL but for RDF/XML, the diff sizes for the Gene Ontology  suddenly become significantly correlated with changes to the obo files (especially if you separate additions and deletions).]

**Comment by sesuncedu** [comment]
@ignazio1977 has recently implemented sorted output for Manchester Syntax, which can be easier to read in github/bitbucket. 

Also, bitbucket will complain about potentially large diffs for large files, even if there are only two lines of changes.  If you insist, it will try and then act all surprised when it works.  github won't even try.
