### ISSUE TITLE
Rdf/xml renderer xml writer error

### ISSUE THREAD

**Issue by JoyW3000** [owlcs/owlapi#467]
I received a SAXParseException on an owl file, which wasn't thrown by the 4.0.2 version.  It's thrown by checkProperXMLLiteral method.  I tried to validate the xml format of the file, and it is fine.  Not sure why it is thrown by the 4.1.3 version.  I attached the "problem" owl file.   

[Book.owl.txt](https://github.com/owlcs/owlapi/files/48655/Book.owl.txt)

**Comment by ignazio1977** [comment]
The exception is as follows:

    Caused by: java.io.IOException: XML literal is not self contained: "
    <owl:Class rdf:about="http://www.w3.org/2002/07/owl#List"></owl:Class>
    <owl:Restriction>
    <owl:onProperty rdf:resource="http://www.w3.org/2002/07/owl#item"></owl:onProperty>
    <owl:toClass rdf:resource="#Author"></owl:toClass>
    </owl:Restriction>
    "
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.checkProperXMLLiteral(XMLWriterImpl.java:446)
	at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeTextContent(XMLWriterImpl.java:433)
	... 19 more
    Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 59; The prefix "owl" for element "owl:Class" is not bound.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)


The problem here is this part of the file:

    <owl:Class rdf:ID="AuthorList">
        <owl:intersectionOf rdf:parseType="owl:collection">
            <owl:Class rdf:about="http://www.w3.org/2002/07/owl#List"/>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.w3.org/2002/07/owl#item"/>
                <owl:toClass rdf:resource="#Author"/>
            </owl:Restriction>
        </owl:intersectionOf>
    </owl:Class>

`owl:collection` is incorrect for the parseType of an intersection; it should be:

`<owl:intersectionOf rdf:parseType="Collection"> `

What happens afterwards is that the rest is parsed incorrectly, and the only matched pattern is that for an XML literal - which is incorrect, indeed, but at this point the content is just garbled.

The XML Literal found is `<owl:Class rdf:about="http://www.w3.org/2002/07/owl#List"/>`, which indeed is not a valid XML literal: xml literals must be self contained and not rely on anything from the surrounding XML file. As this fragment does not define `owl:`, it is not valid.

In 4.0.2, attempting to write an incorrect XML literal was not considered an error; that was a bug, as the spec is clear about what an XML literal is required to be. Incidentally, I consider highly questionable the decision of having embedded XML literals without escaping them, when the only format described in the specs is an XML format. But alas, my hindsight is not useful.

**Comment by JoyW3000** [comment]
Thank you for the explanation.  I'll close the ticket since it's a legit exception.
