### ISSUE TITLE
Hermit not compatible with the latest version of the API

### ISSUE THREAD

**Issue by nimonika** [owlcs/owlapi#473]
It seems like Hermit is not compatible with the current version of the API, I get some runtime errors with it. Is it possible to know which external reasoners would currently detect unsatisfiable classes with the API?

**Comment by ignazio1977** [comment]
HermiT 1.3.8.413 is a fork I've released that is compatible with OWLAPI 4.1.3. Other reasoners are the latest FaCT++, the latest JFact  and Pellet 2.4.0-ignazio1977 (again a fork released for compatibility).

I'm not sure about other reasoners. Konclude is a good bet.

**Comment by sesuncedu** [comment]
It ought to be possible to do some checks using  the Maven animal sniffer
plugin,  since I think most of the incompatibilities show up as method
signature changes. That doesn't do the  fixing though.

The version 4 port of Hermit is faster, slower,  or about the same as the
version 3 edition🤔. The two versions were entered in ORE 2015, and results
are a bit confusing.
Version 4 passed more tests (possibly because the  owlapi side used less
memory, leaving more space for tabbling).

I have hypotheses on how to fix the slowdowns but it is a pain to setup and
run the macro benchmark :)

Doesn't Konclude use an XML bridge? It should be an easy port if so.

I really want to do a good Konclude owlapi bridge, but to really be
effective it's going to require custom implementations of vast chunks of
impl (to have a shared ontology representation).

[My ideal would be to have a default implementation that would be efficient
&  flexible enough to be used by reasoners directly, instead of each
reasoner having its own custom classes. That's Version 5.1 territory]

**Comment by ignazio1977** [comment]
@sesuncedu Interesting ideas about a shareable implementation that satisfies reasoning requirements. I've been meaning to do that in JFact. Pellet and HermiT could provide a good insight on what a tableaux/hypertableaux approach needs in terms of enhancements, although this might need to be wrestled out of the code with a large amount of effort. "Pulling teeth" comes to mind, although dentists tell me that that's the easy part of the job. I don't know whether I should trust them.

Konclude uses OWLLink to connect with OWLAPI; the examples don't make me think that there is a compatibility issue between 3.5 and 4, but I guess the fastest way to figure that out is trying :-)
http://www.derivo.de/products/konclude/usage-owl-api.html
