### ISSUE TITLE
Untyped Individuals extracted from document information

### ISSUE THREAD

**Issue by nimonika** [owlcs/owlapi#477]
When parsing the prov-o ontology with the API, it seems that some part of the document information is extracted as untyped individuals from the document information.
```
<http://www.w3.org/ns/prov-o#>
    a owl:Ontology ;
    rdfs:comment """This document is published by the Provenance Working Group (http://www.w3.org/2011/prov/wiki/Main_Page). 

If you wish to make comments regarding this document, please send them to public-prov-comments@w3.org (subscribe public-prov-comments-request@w3.org, archives http://lists.w3.org/Archives/Public/public-prov-comments/). All feedback is welcome."""@en ;
    rdfs:label "W3C PROVenance Interchange Ontology (PROV-O)"@en ;
    rdfs:seeAlso <http://www.w3.org/TR/prov-o/>, <http://www.w3.org/ns/prov> ;
    owl:versionIRI <http://www.w3.org/ns/prov-o-20130430> ;
    owl:versionInfo "Recommendation version 2013-04-30"@en ;
    :specializationOf <http://www.w3.org/ns/prov-o> ;
    :wasRevisionOf <http://www.w3.org/ns/prov-o-20130312> .
```
Is extracted as 
```
Individual: <http://www.w3.org/ns/prov-o-20130312>

Individual: EmptyCollection

    Annotations: 
        rdfs:label "EmptyCollection"@en,
        definition "An empty collection is a collection without members."@en,
        rdfs:isDefinedBy <http://www.w3.org/ns/prov-o#>,
        component "collections",
        category "expanded"
    
Individual: <http://www.w3.org/ns/prov-o>

Individual: <http://www.w3.org/ns/prov-o#>

    Facts:  
     wasRevisionOf  <http://www.w3.org/ns/prov-o-20130312>,
     specializationOf  <http://www.w3.org/ns/prov-o>
 ```
Is this usual behaviour when parsing ontologies with document information?

**Comment by ignazio1977** [comment]
I think in this case the behavior is expected, although it's hard to tell whether it's right.

The iri of this individual appears as value of wasRevisionOf. wasRevisionOf is declared in the ontology as both annotation property and object property, so in parsing the triple two types are compatible with the grammar, i.e., individual and anyURI literal. There are no type declarations for the iri as individual, bit such declarations are not mandatory, so it's down to the parser to decide whether the object property nature should be considered first.

Also, an annotation property can have individuals as values - so taking it as individual is acceptable for both.

Now to whether this is correct: since in OWL 2DL the property cannot have both natures, we're left guessing. This is OWL Full, so either is fine.

I believe in this case the deciding factor is the lack of a datatype on the tag; without something specifying this is a literal, individual is the best guess that can be made.
