### ISSUE TITLE
Cyclic imports cause illegal punning

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#483]
In sweet 2.3:
[https://sweet.jpl.nasa.gov/sites/default/files/2.3.zip](https://sweet.jpl.nasa.gov/sites/default/files/2.3.zip)  [edit: fixed URL being mangled by markdown - ses] 

hasLowerBound is parsed as a data property and an annotation property.

Pellet is checking for a data property case and assumes that if a property is not a data property it must be an object property. This is always the case for OWL 2 ontologies, but this ontology is not being parsed as an OWL 2 compatible ontology - punning of an annotation property and a data property is not allowed.

It's a parsing issue. hasLowerBound is declared in relaMath.owl as data property. However relaMath.owl imports reprMath.owl, which uses hasLowerBound but does not declare it. reprMath.owl imports relaMath.owl, so there is a cyclic import there.

The problem is that, during parsing: - relaMath.owl is parsed, import is found, reprMath.owl import is resolved; no declarations are parsed yet. - reprMath.owl is parsed, import is found. relaMath.owl is already being parsed, so call does nothing. All entities declared in relaMath.owl are included while parsing reprMath.owl. PROBLEM: the entities have not been parsed yet, so this set is empty. hasLowerBound is found in reprMath but no declaration exists yet. Therefore OWLAPI defaults to AnnotationProperty. - relaMath.owl parsing continues, declaration is found.

Final result: Any ontology importing relaMath.owl has illegal punning for hasLowerBound. OWLAPI bug.

Workaround: Add data property declaration to reprMath.owl:

<owl:DatatypeProperty rdf:about="#hasLowerBound"/>

This might need to be done in more than one ontology. The bug affects all OWLAPI versions.

**Comment by ignazio1977** [comment]
To replicate:

relaMath.owl

    <?xml version="1.0" encoding="UTF-8"?>
       <rdf:RDF 
           xml:base = "http://sweet.jpl.nasa.gov/2.3/relaMath.owl"
           xmlns:math = "http://sweet.jpl.nasa.gov/2.3/reprMath.owl"
           xmlns:owl = "http://www.w3.org/2002/07/owl#"
           xmlns:rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#">
       <owl:Ontology rdf:about="">
           <owl:imports rdf:resource="http://sweet.jpl.nasa.gov/2.3/reprMath.owl"/>
       </owl:Ontology>
       <owl:DatatypeProperty rdf:about="#hasLowerBound"/>
    </rdf:RDF>

reprMath.owl

    <?xml version="1.0" encoding="UTF-8"?>
    <rdf:RDF 
        xml:base = "http://sweet.jpl.nasa.gov/2.3/reprMath.owl#"
        xmlns:mrela2= "http://sweet.jpl.nasa.gov/2.3/relaMath.owl"
        xmlns:owl = "http://www.w3.org/2002/07/owl#"
        xmlns:rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#">
        <owl:Ontology rdf:about="">
            <owl:imports rdf:resource="http://sweet.jpl.nasa.gov/2.3/relaMath.owl"/>
        </owl:Ontology>
        <owl:Class rdf:about="#Interval"/>
        <Interval rdf:about="#NormalizedRange">
            <mrela2:hasLowerBound rdf:datatype="http://www.w3.org/2001/XMLSchema#double">0</mrela2:hasLowerBound>
        </Interval>
    </rdf:RDF>


Code:

        OWLOntologyManager m = OWLManager.createOWLOntologyManager();
        OWLOntology o = m.loadOntologyFromOntologyDocument(new File("relaMath.owl"));

    class uk.ac.manchester.cs.owl.owlapi.OWLDataPropertyImpl	<http://sweet.jpl.nasa.gov/2.3/relaMath.owl#hasLowerBound>
    class uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl	<http://sweet.jpl.nasa.gov/2.3/relaMath.owl#hasLowerBound>

**Comment by sesuncedu** [comment]
I was wondering if this bug might be present but didn't check in case it was. 

The canonical parse process seems in the general case to require delaying parsing until all declarations have been extracted from the imports closure.  This has the potential for bad interactions with RDF lax parsing and property type guessing.  

Detecting the problem isn't too hard (check guessed property types for consistency across the import closure). 

Fixing the problem is harder, since misgendered properties require either patching or re-parsing.  
Data and object properties are guessed when there is supporting evidence,  so a clash of those types is definitely a signal of illegal punning. So the first step is checking all such guesses and declarations for consistency.  A clash of guesses could indicate annotation property, but any use other than assertions becomes a real problem. 

Annotation properties are generally fallback guesses, so a more definitive guess of data or object property is less problematic. 
Unless,  of course,  the property was used in an axiom annotation. 

Conformance with the spec only requires declarations to be taken into consideration, which makes the problem less complicated ; reparsing with the declaration in scope is enough. 
Though if an ontology manager contains an ontology that is imported by two others, and the importers have different types for a property not declared in the imported ontology the whole model breaks.

**Comment by ignazio1977** [comment]
> Detecting the problem isn't too hard (check guessed property types for consistency across the import closure).
> 
> Fixing the problem is harder, since misgendered properties require either patching or re-parsing.

My thoughts exactly, but then most issues with parsing seem to follow this pattern.

I'm wondering if part of the problem is not recognizing  the pitfalls other languages have avoided.
OWL properties have the same characteristics of variables in strongly typed languages - and both C and Java require the class of a variable to be imported explicitly in each file using it. The OWL spec didn't include that nugget of wisdom, hence our present plight `</humour>`.

**Comment by ignazio1977** [comment]
I'm thinking that, along the lines described [here](https://www.w3.org/TR/owl2-syntax/#Canonical_Parsing_of_OWL_2_Ontologies), we need to parse declarations first, then parse the rest of an ontology.

I'm worried about the performance problems associated to what is potentially a double scanning of the input.

**Comment by sesuncedu** [comment]
Only the parse results are required to match, so if all types are present in the first pass,  there is no need for a second go around.  This will be true by default for documents generated by owlapi. 

If all required declarations are present in the document or have already been seen, the OWLOntology can be built in one pass.  

If entity types have been inferred due to the use of a strongly typed format like FSS,  those can be treated as strongly as declarations. 

The ontology mangler could keep a known IRI -> entity types map scoped to top level loading,  which could be used / updated in the places where entity types are currently checked during the parse.  Encountering an unknown type  could trigger the slow path; the results of the  current parse could be discarded, but processing continued in a perfunctory fashion with only declarations / inferred  + guessed typing being gathered (together with info on IRIs with unknown types, and which ontologies and documents they were seen in). 

There may be a need to record sets of properties that are constrained to be the same type if that type is unknown. 

If the initial parsing process finishes with no unknown types,  there is no reparsing necessary. If there were guessed types,  then the document only needs to be reparsed if the guess was subsequently invalidated. 

  If there are entity references whose type is only guessable, then the most specific property type can be chosen.  Only type deprived documents need be reparsed. 

Ontology managers that contain more than one root ontology,  with different declarations for entities in an imported ontology, will give incorrect results unless a major reworking of the api is performed.  

The sheer amount of work for just a few edge cases is...  unsurprising. 

OTOH,  it would be an excuse for a do-over of the RDF translation code.

**Comment by sesuncedu** [comment]
I can't remember if the rdf rendering code pre-declares types (I don't think it does). If it doesn't then it might possibly be worth it.  Only forward references need to be declared,  but a complete set of declarations might be more stable for VCS purposes.

**Comment by cmungall** [comment]
Hi, we are still having issues with these Error classes being generated in the latest SWEET

https://github.com/ESIPFed/sweet/issues/84#issuecomment-552550082

I'm afraid I have not been able to do much to track down the source, it's very hard to debug to see if the parse error is caused by incomplete or conflicting declarations in SWEET or if there is still a lingering bug in the owlapi.

**Comment by ignazio1977** [comment]
Pretty sure there's at least one bug, there are open issues tracking that topic. Very hard to fix incrementally, I'm trying to redesign the whole parser but it's a nasty task.

**Comment by lewismc** [comment]
@ignazio1977 can you point us at the open issues please? I'm keen to fix this in SWEET as it has been lingering for some time now.

**Comment by ignazio1977** [comment]
First page of issues in the tracker: #798

**Comment by lewismc** [comment]
Thank you

**Comment by ignazio1977** [comment]
If it helps, looks like the problems are in these ontologies:

    LoadSweet.main() OntologyID(OntologyIRI(<http://sweetontology.net/reprMath>) VersionIRI(<null>))
    SubClassOf(<http://sweetontology.net/reprMath/OrderedPair> <http://org.semanticweb.owlapi/error#Error1>)

    LoadSweet.main() OntologyID(OntologyIRI(<http://sweetontology.net/reprMathGraph>) VersionIRI(<null>))
    SubClassOf(<http://sweetontology.net/reprMathGraph/Edge> <http://org.semanticweb.owlapi/error#Error10>)
    SubClassOf(<http://sweetontology.net/reprMathGraph/Graph> <http://org.semanticweb.owlapi/error#Error11>)
    SubClassOf(<http://sweetontology.net/reprMathGraph/Graph> <http://org.semanticweb.owlapi/error#Error12>)

    LoadSweet.main() OntologyID(OntologyIRI(<http://sweetontology.net/reprMathOperation>) VersionIRI(<null>))
    SubClassOf(<http://sweetontology.net/reprMathOperation/DefiniteIntegral> <http://org.semanticweb.owlapi/error#Error16>)
    SubClassOf(<http://sweetontology.net/reprMathOperation/IndefiniteIntegral> <http://org.semanticweb.owlapi/error#Error13>)
    SubClassOf(<http://sweetontology.net/reprMathOperation/Integral> <http://org.semanticweb.owlapi/error#Error14>)
    SubClassOf(<http://sweetontology.net/reprMathOperation/Integral> <http://org.semanticweb.owlapi/error#Error15>)

**Comment by cmungall** [comment]
it's still really hard to figure out why these class expressions are
failing to parse, they look valid in the source

**Comment by lewismc** [comment]
I also spent some time looking at this today. Using protege master branch, analyzing the terminal output and manually inspecting both asserted and inferred (FaCT++ reasoner) axioms I can't see the source of the errors either. 
I do see lots of the following
```
...
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaTime/dayOfYear in punning not allowed [DataProperty: dayOfYear, AnnotationProperty: dayOfYear]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaSci/hasNumericValue in punning not allowed [DataProperty: hasNumericValue, AnnotationProperty: hasNumericValue]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaPhysical/hasCharge in punning not allowed [DataProperty: hasCharge, AnnotationProperty: hasCharge]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaPhysical/moreVisibleThan in punning not allowed [ObjectProperty: moreVisibleThan, AnnotationProperty: moreVisibleThan]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaMath/hasScalingNumber in punning not allowed [AnnotationProperty: hasScalingNumber, DataProperty: hasScalingNumber]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaTime/moreFrequentThan in punning not allowed [ObjectProperty: moreFrequentThan, AnnotationProperty: moreFrequentThan]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaTime/hasStartTime in punning not allowed [ObjectProperty: hasStartTime, AnnotationProperty: hasStartTime]
Illegal redeclarations of entities: reuse of entity http://sweetontology.net/relaSpace/oppositeTo in punning not allowed [ObjectProperty: oppositeTo, AnnotationProperty: oppositeTo]
...
```

**Comment by cmungall** [comment]
Well, these warnings are true positives, these need to be fixed in SWEET. 

```
$ egrep 'dayOfYear.*type' *ttl
relaTime.ttl:trela:dayOfYear rdf:type owl:DatatypeProperty ;
reprTimeSeason.ttl:trela:dayOfYear rdf:type owl:AnnotationProperty .
```

These could potentially even be the source of the parse errors (although it may be entirely unrelated). Do you want to make a ticket for these in the SWEET repo Lewis?

**Comment by lewismc** [comment]
yes I will do

**Comment by ignazio1977** [comment]
I have a couple of ideas about small changes to the sweet ontologies that might fix this issue. I'll update you once I got a chance to try.

**Comment by ignazio1977** [comment]
@cmungall @lewismc conflicting declarations when one is an annotation property might be consequences of older saves, I'm fixing them in my changes to fix the parsing errors. I've found one actual bug though, a property declared as data and object property in the same file. that one needs to be fixed by a domain expert.

**Comment by ignazio1977** [comment]
These bad punnings are not related to the parse errors, they're kind of the symmetric issue - not enough declarations in one case, too many in the other. However, the workaround for one and the fix for the other look basically the same, so I'll do them all at once.
