### ISSUE TITLE
Annotated entities not declared in RDF/XML

### ISSUE THREAD

**Issue by vincentvialard** [owlcs/owlapi#511]
Hi there,

I stumbled upon a weird behaviour while trying to extract annotations of ontologies that use custom datatypes for the litterals of the annotations. 

I collect the annotation assertions of an ontology, create a new ontology with the collected axioms and save it. Declarations for the custom datatypes are automatically added, except if they are annotated. 

I suppose it's because if they are not annotated, the serializer does not know them, and he adds a declaration when he finds them as type of the litterals. But the OWL-XML serializer adds the declaration even for the annotated datatypes. 

I don't know what's right here, and it's not really a problem for my usage. But it feels weird and might be the sign something is wrong under the hood.

A minimal test with results is here: [Archiv.zip](https://github.com/owlcs/owlapi/files/210522/Archiv.zip)

Best,

Vincent.

**Comment by ignazio1977** [comment]
Annotation or no annotation on an entity should not make a difference to adding declarations - unless the annotation assertion is covering the declaration role, but that seems incorrect.

**Comment by ignazio1977** [comment]
The check for undeclared entities happens after both declarations and annotations assertions have been added to a set - and tests if the set is empty. From memory, this is because the annotation assertions have been included after the first part of the code was written, as a fix for duplicate annotations for punned entities.

In other words, bug. It's in RDFRendererBase, which is not involved in OWL/XML rendering, so that explains why OWL/XML works fine.
