### ISSUE TITLE
OWLImmutableOntologyImpl.java omits null check

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#517]
I'm getting a periodic error like this:

    OWLImmutableOntologyImpl.java:  842  uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl/getImportsClosure
    ConcurrentOWLOntologyImpl.java:  190  uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl/getImportsClosure
              OWL2Profile.java:   77  org.semanticweb.owlapi.profiles.OWL2Profile/checkOntology
                   profile.clj:   50  tawny.profile/eval326782/inprofile?
                       owl.clj:  490  tawny.owl/default-ontology

I haven't got a simple test case reproduction yet, but the problem occurs when
getOWLOntologyManager returns null. This isn't supposed to happen, but I think
could be caused because the constructor has a null check:

    public OWLImmutableOntologyImpl(@Nonnull OWLOntologyManager manager, @Nonnull OWLOntologyID ontologyID) {
        this.manager = checkNotNull(manager, "manager cannot be null");
        this.ontologyID = checkNotNull(ontologyID, "ontologyID cannot be null");
    }

but, alas, the setOWLOntologyManager method does not.

    @Override
    public void setOWLOntologyManager(OWLOntologyManager manager) {
        this.manager = manager;
    }

**Comment by ignazio1977** [comment]
This is required by the ability to move an ontology from a manager to another. There was a bug in this area - can you confirm which version you are using?

Aside from that, this might be due to using an ontology after it has been removed from a manager - when it should be in an illegal state, technically.

**Comment by phillord** [comment]
My original problem went away when I upgraded to 4.2.3, but I left the bug report in case it helps. I understand why you need setOWLOntologyManager, but does it need a null state in between?

**Comment by ignazio1977** [comment]
That's a bit tricky, because an ontology can be removed from a manager (without being assigned to a new one), but we have no control on whether the ontology is still referenced someplace else. So, if `getOWLOntologyManager()` returns the old manager, it is lying - and other things like save() and getFormat() will be unreliable. Setting the field to null stops the lie, but creates other failures.

I can't find a clean solution that avoids all of the issues above, in the current architecture - there's too much stuff that's delegated to the manager, for a number of reasons: saving format, saving preferences, modifications, etc. On the other hand, while we could redistribute some of these responsibilities, we can't do so without rearchitecting a core part of the API.

All doable, in time, but not an easy transition.

**Comment by phillord** [comment]
Tricky -- best I can think off hand is a NullOntologyManager. Although, in the end, what can this actually do other than either except or cause a (confusing) no-op.
