### ISSUE TITLE
HasApplyChanges.applyChanges returns ChangeApplied

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#544]
This used to return a list of the applied changes.  It's not clear what happens now if only some of the changes were applied i.e. only a subset of axioms were added in a set of add axiom changes.  It seems like the only way of determining what was applied is to use a listener, which is messy.

What was the motivation for the interface change here?

**Comment by ignazio1977** [comment]
The change was to add transactional properties. If the returned value is unsuccessful, no changes have been applied.

**Comment by matthewhorridge** [comment]
I think the javadoc could do with updating because I don't think it's clear what this means compared to what it used to mean.  

Could a result object be returned instead (or a new interface/method added) that includes the currently returned flag and the list of changes that were actually applied?

I'm under the impression that it used to be the case that  ```AddAxiom(O, SubClassOf(A, B))``` would not be applied if ```O``` already contained ```SubClassOf(A, B)```.  This was the case wasn't it?

**Comment by ignazio1977** [comment]
> I'm under the impression that it used to be the case that AddAxiom(O, SubClassOf(A, B)) would not be applied if O already contained SubClassOf(A, B). This was the case wasn't it?

Indeed. `ChangeApplied.NO_OPERATION` would be the value returned in this case.

**Comment by ignazio1977** [comment]
Different method with return object seems a good idea. Version 4.3.0 and 5.1.0 respectively?

**Comment by matthewhorridge** [comment]
Sounds good to me.  I'm just wondering what the new method name will be.  I'm also wondering whether it might be useful to add a context object as a parameter.

**Comment by matthewhorridge** [comment]
Any chance of a better method name?  The current one makes it sound like it's the changes that are detailed rather than the return object.  Of course, I don't have any good suggestions :)

**Comment by ignazio1977** [comment]
I'm open to suggestions, this was the best I could make up

**Comment by matthewhorridge** [comment]
applyChangesAndGetDetails?

**Comment by ignazio1977** [comment]
If you're happy with a longer name I won't complain :-)

**Comment by matthewhorridge** [comment]
Well, my IDE will complete it for me :)

**Comment by sesuncedu** [comment]
On Feb 9, 2017 1:26 PM, "Matthew Horridge" <notifications@github.com> wrote:

Well, my IDE will complete it for me :)

Nice *idea* :-)

Of course, the whole approach  of explicitly creating change objects and
applying them is problematic.

A different paradigm would be to make changes to the appropriate entity,
and have the appropriate notifications generated by the system and posted
to a whiteboard if there are subscribers.
For example, there would be addSubclass/addSuperclass methods on
OWLClass(Expression) , and the relation  would be stored in that fashion.
It could even be possible to record transient inferred subs & supers in a
similar fashion (though not directly on the entity). There should also be
methods for adding slots (properties), and specifing their ranges
/cardinalities directly on a class. The actual axioms should be happening
on the scene.

It should also be possible to set properties on the "class", with
annotation properties going to a class object, and ob/data properties going
to the named individual with the same IRI. The punning should be hidden by
default, but with more sophisticated apps  being able to split the view.

Just because everything is subsumption does not mean everything should look
like subsumption :)  Only the wise and the  reasoners need think that way.

This should be copied to a separate issue (when I'm not on a tablet and
sleeping pill :)
