### ISSUE TITLE
Structural sharing in GCIs causes errors

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#564]
Case 1:

If we have an axiom `R some Y SubClassOf R some Y`

(which is of course tautological but nevertheless is structurally allow, and could end up in ontology if someone makes a mistake in Protege)

then this results in a `_:genid1` in the conversion to RDF/XML, which yields 'Error1' is various displays

Example input:

```
Ontology(<http://x.org/test.owl>
SubClassOf(ObjectSomeValuesFrom(<http://x.org/part-of> <http://x.org/Foo>) ObjectSomeValuesFrom(<http://x.org/part-of> <http://x.org/Foo>))
)
```

Case 2:

If we have an axiom `R some Y SubClassOf (S some (R some Y))`

The axiom is lost completely on translation to RDF/XML. This is actually a reasonable GCI to have in some ontologies.

Example ontology:

```
Ontology(<http://x.org/test.owl>
SubClassOf(ObjectSomeValuesFrom(<http://x.org/part-of> <http://x.org/Foo>) ObjectSomeValuesFrom(<http://x.org/located-in> ObjectSomeValuesFrom(<http://x.org/part-of> <http://x.org/Foo>)))
)
```

It seems likely that It seems likely that when translating to RDF the same blank node is being used for the expression on the LHS and the identical expression or sub-expression on the RHS, and this is not being "de-shared" correctly.

**Comment by ignazio1977** [comment]
The error would be to use blank nodes at all - the appearance of a genid string means they're being treated as individuals (where multiple appearances are not structure sharing), while class expressions, like in your examples, should not be translated to triples that way at all.

**Comment by ignazio1977** [comment]
So this is shaping as an interesting one:

- first thing is, this is not new. We've met the same problem before, and attempted a fix - `_x subclassOf _x` should have taken care of this problem. Apparently it did not.

- We lose track of the root node for general axioms: a blank node is found to appear as both subject and object of one or more triples, and therefore not considered a root. So the rendering does not happen correctly

- After correcting for this issue, the next problem is that the two appearances of the node create the same triples twice. As they are stored in a set before the actual rendering, the duplicates are lost; when the rendering takes place, the second node loses triples.

- This started to ring a bell. Sure enough, we put in place a fix for the same kind of problem in the RIO renderer, because of duplicate triples with explicit node ids being lost. Looks like the fix needs lifting in the general RDF renderer.
