### ISSUE TITLE
PlainLiteralTypeFoldingAxiomSet

### ISSUE THREAD

**Issue by ShadowWalker627** [owlcs/owlapi#565]
why I get this error:"PlainLiteralTypeFoldingAxiomSet cannot be resolved to a type"

**Comment by ignazio1977** [comment]
That class is part of the test package. If you're trying to use these classes, you have to add the source code in the contract subpackage to your project.

**Comment by ShadowWalker627** [comment]
oh,thanks!! Could I beg for all the  external dependencies jar. Because I can not build an maven project, because i am not familiar with its operation.

**Comment by ShadowWalker627** [comment]
Can I use this owlAPI parse my owl files, and then, import it to the neo4j db?

**Comment by ignazio1977** [comment]
You don't need to build from scratch to use owlapi in another project, just add a maven dependency to owlapi-distribution.

We don't release a jar with the tests because it is large and unneeded for anyone not developing the  owlapi itself.

Owlapi can be used to write a neo4j loader but there is nothing ready made for this - I believe others have implemented such a connector but I do not have a link for it.

**Comment by ignazio1977** [comment]
See issue #584 for a non maven solution
