### ISSUE TITLE
OWLOntologyManager in OWLImmutableOntologyImpl should be @Nullable

### ISSUE THREAD

**Issue by ykazakov** [owlcs/owlapi#568]
[here](https://github.com/owlcs/owlapi/blob/f701672d2bc82eec129c53d6cccfb2e8aa32c83b/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLImmutableOntologyImpl.java#L47) is documented to be @Nonnull and it is checked on non-null in the [constructor](https://github.com/owlcs/owlapi/blob/f701672d2bc82eec129c53d6cccfb2e8aa32c83b/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLImmutableOntologyImpl.java#L59), yet for some reason the argument is not annotated with @Nonnull. But there is no such a check in the [set method](https://github.com/owlcs/owlapi/blob/f701672d2bc82eec129c53d6cccfb2e8aa32c83b/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLImmutableOntologyImpl.java#L81), where the argument is actually annotated as @Nullable. Shouldn't it raise red flags by the annotation checker? In fact it can happen that this field is set to null, e.g., [here](https://github.com/owlcs/owlapi/blob/f701672d2bc82eec129c53d6cccfb2e8aa32c83b/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLOntologyManagerImpl.java#L1062).
I suggest also to check for similar inconsistencies in other implementations of OWLOntology and maybe for other @Nonnull fields. (The best would be, of corse, to verify on null such fields every time they are set).

**Comment by ignazio1977** [comment]
Indeed, it raises warnings.

The problem here is that an ontology needs a manager to be created, and for a number of operations; however, it can be removed from a manager, either definitively or to be moved to a different manager.

Best solution for this is to allow the field to be null and throw an exception whenever a null manager is used - as this indicates attempting to use an ontology that should no longer be used.

**Comment by ykazakov** [comment]
I understand the problem, I just was puzzled when I got an NPE on the field that was annotated @Notnull. So you say that the ontology should be not used if the manager is null. Should then any method called on this ontology throw exception? 
Furthermore, why not to prevent setting this field to null completely? E.g., when the ontology is removed from a manager, couldn't it be just moved to a freshly created manager? If it is no longer used, everything will be garbage collected, but it can also be used without getting exceptions.

**Comment by ignazio1977** [comment]
>  So you say that the ontology should be not used if the manager is null. Should then any method called on this ontology throw exception? 

The exact intent would be to have the equivalent of free(), but there's no such thing in Java. Most methods will fail - saving, working with the imports closure, etc. Listing axioms still works. It would be doable to add a manager check to all of these and ensure exceptions are thrown uniformly, although I don't think it's a high priority - far as I can tell most code never removes ontologies from managers, it just gets a new manager when one is no longer in scope.

> couldn't it be just moved to a freshly created manager?

Uhm I'm not sure this is a good idea; if a code path removes the ontology from its original manager and a reference to the ontology is kept somewhere else, the ontology will change behaviour (e.g., axioms in import closures will no longer be listed) - but it will be really hard to find out what the bug is. Import closure issues are quite hard to debug as it is (there's one currently open where the same code behaves differently even under apparently the exact same conditions).

Reading this again, I think I just argued myself into the need for all methods to throw exceptions if the manager has been nulled.

**Comment by ignazio1977** [comment]
Looking at the method implementation, any method that relies on the import closure should fail (because the ontology is no longer connected to its imports closure, held in the manager). No changes can be made either, and no saving. However, access to axioms defined in the ontology, containment check, ontology signature - these won't change behaviour and can be used safely.

It's also hard to ensure null checks before any other method is called, especially in extensions and alternative implementations (if any exist) - however, actual usages of the manager are covered. Any call to getOWLOntologyManager() will fail with a meaningful exception, specifying the ontology does not have a manager.

**Comment by ykazakov** [comment]
So you are saying it is still OK to use a removed ontology so long the manager is not involved? Thus, no exception should be thrown, e.g., for listing axioms?

Regarding the exception thrown on getOWLOntologyManager(), in what way is it better than NPE? In NPE one can also clearly see that the manager is null. And the new exception is not much better in explaining why it became null.

I understand your reasoning regarding the import closure, but what happen if the removed ontology was imported by some other ontology? Is there a check for that?

**Comment by ignazio1977** [comment]
I've revised the message so that it's clearer that the error (is likely to) depend on using an ontology after it has explicitly been removed.

Regarding imported ontologies removed from a manager and their continued use, you are correct that listing axioms will work as before; for ontologies importing the removed ontology, they will behave the same as if the imported ontology had been unloadable and the manager was configured to ignore import errors.

I'm unsure if this is a problem; I expect the most common use case for removing an ontology to have the ontology removed as the root of an import closure, rather than one of the intermediate branches; in which case, each remaining ontology would be the root to its own closure, and be self consistent. (Excluding cycles in the import closure, of course, in which case this does not apply)
