### ISSUE TITLE
Zip with dependencies included for non Maven users

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#584]

**Comment by ignazio1977** [comment]
The jar will contain owlapi-distribution and all the required dependencies. Might as well be an OSGi bundle, since there is no disadvantage to having a manifest.mf file included.

As it is not thought for maven users, it does not need to be released on Maven Central and it will be placed in the https://github.com/owlcs/releases project

**Comment by ykazakov** [comment]
I would suggest to still release this zip/jar to maven central. This way at least it is not going to be outdated as it is now. One can then easily provide a link to download the latest release.

**Comment by ignazio1977** [comment]
To be released on maven central it also needs source and javadoc artifacts - it basically becomes a new module, complicating (well, overcomplicationg) build and maintenance.

owlapi-distribution, owlapi-osgidistribution, uberzip - all to deal with slightly different use cases for client code. It's already snowballed to larger than necessary proportions, I'd rather not make it worse.

I'm actually considering having the aggregate modules split to a separate release process; this would allow, for example, a release that includes owlexplanation as replacement for the explanation code without creating circular dependencies. Might help with satisfying more varied requirements, too.

**Comment by ykazakov** [comment]
We have been releasing zip files for ELK on maven central without problems. See, e.g., [here](http://repo1.maven.org/maven2/org/semanticweb/elk/elk-distribution/0.4.3/). Everything is managed by one maven module (elk-distribution). One module can have several other artifacts, not only jar, sources or javadoc. You can put into zip files whatever you want.

Regarding a large number of distribution formats, perhaps one should revise them. I am not sure, for example, why one needs owlapi-osgidistribution. To my knowledge, it is only used in Protege. But since Protege has migrated to maven, I don't see why it could not instead include the necessary owlapi modules directly and embed non-bundle dependencies itself (like it already does with its own non-bundle dependencies). Likewise, I also not sure why owlapi-distribution is useful. If one uses maven, one can add dependencies to the necessary owl-api modules, if not, one also probably needs all other dependencies, so the uberzip seems more convenient to use.

**Comment by ignazio1977** [comment]
:-) following that line of thought, neither of the maven aggregates is necessary for Maven users, so we could cut both, but then either we don't put the uberjar on Maven either or we need source and javadoc for it because there is no other aggregate being released to maven to which the uberjar can be attached.

The reasons you presented are basically the same reasons why I'm considering splitting the aggregates to a separate project - at which point it would make sense to reevaluate how the uberjar gets produced and updated.

**Comment by ykazakov** [comment]
> But, the uberjar is not for maven users - so maven central is just a convenient place for it, but not necessarily the best one, as non maven users are not that likely to go looking for it there...

When one finds a better permanent and convenient location to store all releases, one can certainly use that. We have previously used a google code website until it was closed :-(. 
The advantage of maven central is that one does not need to make any additional configuration for uploading the files. All artifacts are automatically uploaded during the release. For example, all releases of Protege for all platforms are [there](http://repo1.maven.org/maven2/edu/stanford/protege/protege-desktop/5.2.0/). 
The users of course will not go to maven central. They will go to the OWL API website. However,  it is easy to provide a link to the latest version of OWL API on maven central [using Rest API](http://search.maven.org/#api) without worrying too much about updating it.

> The reasons you presented are basically the same reasons why I'm considering splitting the aggregates to a separate project

Not sure I follow that. I said that I do not see much reasons for having any aggregate jar/zip except for the one that contains all of the OWL API plus its dependencies. This should be used primarily by non-maven users. I don't see much benefit in splitting it to several files. As I mentioned, you can configure maven to put into the zip any files and folders you like, including aggregated jar for the whole owl-api, jars for every dependencies, sources for these files, README, examples, etc.
