### ISSUE TITLE
Problems compiling version5 for Android v24 Nougat

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#585]
There is some weird generics / type inference stuff going on when trying to compile against android v24. 

Specifically, with the v24 libraries, the javac (and intellij) both think that the orElseThrow call might throw a ```Throwable```.  With the standard jdk8 class libraries, there is no problem. 
Oddly, the source for both versions of Supplier and Optional appears to be basically identical, and inlining orElseThrow(), with appropriate getters, compiles fine. 

```java
    public static OWLFacet getFacet(IRI iri) {
        checkNotNull(iri, "iri cannot be null");
        return stream().filter(v -> v.iri.equals(iri)).findAny()
            .orElseThrow(() -> new IllegalArgumentException("Unknown facet: " + iri));
    }
``` 

This only seems to affect a couple of places; I have work arounds, but I don't want to apply them until I have a better idea what the real problem is. 
Also, I am not convinced that IllegalArgumentException is the right exception here.

Also, OWLFacet creates a static (LinkedHash) set of IRIs. Since Sets are implemented as wrappers around maps, there doesn't seem to be any good reason not to create a map and avoid the whole linear search in the first place.

**Comment by ignazio1977** [comment]
Rings a bell with recent build errors I've seen since updating to Eclipse Oxygen - they were in places where a functional interface is expected but none was explicitly mentioned.

E.g., 

    public static <T> List<T> asListNullsForbidden(Stream<T> s) {
        return asList(s.map(x -> checkNotNull(x)));
    }

This complained until I changed to a method reference:

    public static <T> List<T> asListNullsForbidden(Stream<T> s) {
        return asList(s.map(OWLAPIPreconditions::checkNotNull));
    }

In a test, 

    @Parameters
    public static List<AxiomBuilder> getData() {
        return Arrays.asList(
            // With this explicit cast, no problem; without, problem
            // (AxiomBuilder)
            () -> singleton(SubPropertyChainOf(Arrays.asList(propA, propB, propC), propD))
            );
    }

So it looks like there are situations where the compiler should (indeed, used to) figure out the correct functional interface to use for the lambda, but doesn't - I've seen similar issues in the past when updating SDK versions.

Casting to a Provider<IllegalArgumentException> should do the trick, if a bit verbosely.

**Comment by ignazio1977** [comment]
This should fix the problem removing the whole orElseThrow shenanigans.
