### ISSUE TITLE
Parsers and Renders should be split into separate modules

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#592]

**Comment by ignazio1977** [comment]
Not sure I see the advantage. Jumping from parser to renderer code is easy in the current structure; what do we gain from a split?

**Comment by ignazio1977** [comment]
@whitten parsing with more than one parser is necessary for those serialization languages (the majority) where the language cannot be detected from a header or similar info, but this has no relation with the renderers (except for the overlap with RIO parsers and renderers, there is usually only one parser and one renderer for each language).

I'm not clear on what you mean by single renderer code?

**Comment by sesuncedu** [comment]
What I meant in the initial issue was splitting individual format parsers + renderers into separate artifacts, so that there is no need for an application that only wants FSS support to pull in RDF etc. 

This is similar to the way that RIO is packaged.

**Comment by ignazio1977** [comment]
OIC. That's how it used to be - there are some advantages to being able to ditch a few classes, but there is added burden during maintenance. I think it currently makes sense for RIO because of all the dependencies that module has - skipping it reduces the number of transitive dependencies quite a lot. Not so much so for the other parsers and renderers though.

Some languages are there because of legacy - the KRSS formats, for example - and I wouldn't mind them being outside the core. OWL/XML I'm not sure - how alive is it in the wild?
Functional, Manchester and RDF/XML are pretty much core. Turtle I'd like to remove altogether - I believe the Rio Turtle format is better supported anyway.

Looking ahead to better openrdf integration, I wonder about the RDF based formats in their entirety - there might be an advantage in being rid of them, if compatibility with existing OWL ontologies is good. But overall I'd be for deletion rather than separation. I LOVE the delete key.

**Comment by ansell** [comment]
The Rio Parsers should be equivalent, but the Rio Writers are generally focused on high-throughput streaming and don't support pretty-printing as well as the RDF/XML and Turtle renderers here. I have been working on improving the pretty-printing support for the Rio Turtle Writer but it isn't a complete package yet.

**Comment by ignazio1977** [comment]
The rendering is much simpler than the parsing though, so that would still be a plus...
