### ISSUE TITLE
IRIMapper specifies file:// but loading ontology gets http://?

### ISSUE THREAD

**Issue by alanruttenberg** [owlcs/owlapi#608]
I was trying to figure out how my ontology had an axiom I didn't have in the source file, and tracked it down to an import being loaded from other than where the mapper told it to. Before I invest too much time in trying to create a reproducible bug, does this ring a bell? I'm using "net.sourceforge.owlapi/owlapi-distribution/4.2.6"

**Comment by alanruttenberg** [comment]
Sigh. Problem found. Mapper was doing the right thing, but catalog.xml from which it was loading got corrupted.

**Comment by sesuncedu** [comment]
Catalog support is something that could be reconsidered come jdk9, since
there's a public api (and the old internal implementation is likely going
to be locked down by jigsaw).

http://openjdk.java.net/jeps/268

Of course it's the construction of the catalog that is the real pain
(especially if some hypothetical person were to be foolish enough to
attempt to open a file in one's home directory in Protégé. Again. )

**Comment by ignazio1977** [comment]
> attempt to open a file in one's home directory

Or in the folder where they keep literally five thousand ontologies.

/whistles past graveyard
