### ISSUE TITLE
Specify RioSetting values for Rio renderers

### ISSUE THREAD

**Issue by marianobntz** [owlcs/owlapi#614]
Hello, is there a way to render json-ld directly from ontology manager and specifying some config settings, like JSONLDSettings.JSONLD_MODE (JSONLDMode.COMPACT) or I have to use Rio API directly?

I don´t seem to find a way to get the writer config from the owl api...

Thanks

**Comment by ansell** [comment]
The OWLAPI doesn't currently have the ability to pass RioSetting's through other than through direct setting of the RDFHandler on the relevant implementation classes, RioStorer https://github.com/owlcs/owlapi/blob/version5/rio/src/main/java/org/semanticweb/owlapi/rio/RioStorer.java#L187

I will look into adding this feature when I get a chance.

**Comment by marianobntz** [comment]
Thank you! look forward for your fix! :)

**Comment by ignazio1977** [comment]
OWLDocumentFormat has a map of generic parameters that can be passed across - we need to make the storers take notice of them.

**Comment by sathyamoorthyrr** [comment]
Any pointers on how to do this?

**Comment by ignazio1977** [comment]
This will put a parameter in the format map, which RioStorer can access.
This is existing functionality, so it can be done in any OWLAPI version. 5.1.18 will be the first version where it works, once it's released.

There's a bug in RDF4J I spotted while doing this work (https://github.com/eclipse/rdf4j/issues/2661)
While that bug is still open, OWLAPI will try to set the RioSetting objects it knows about; it's possible that not all settings will work.

        RDFJsonLDDocumentFormat format = new RDFJsonLDDocumentFormat();
        format.setParameter(JSONLDSettings.JSONLD_MODE, JSONLDMode.COMPACT);
