### ISSUE TITLE
Change package prefix to owlapi6

### ISSUE THREAD

**Issue by sesuncedu** [owlcs/owlapi#617]
The existing grouping of classes and packages is rather influenced by historical descent, and the existing API can be awkward to learn and use. 
However, it is important to support legacy applications and providers.  The current result is that bug fixes often have to be applied to three different branches. 

If we take the current set of classes, and essentially rename them all into project-internal implementation classes, the existing package and class namespace can be used to implement a  wrapping over the internal implementation that can support the older apis, whilst allowing these internals to be radically refactored, with very different internal structure and public API. 

It might even be worthwhile defining an intermediate legacy-support API that would be used for these legacy apis (every problem in computing can be solved by adding a layer of abstraction, except for the ones that are solved by removing a layer of abstraction). 

There are a few obvious lurking problems. 

One is language level. For example, it used to be impossible to use Java 8 language features on Android. Now it is possible to use  lambdas and method handles on older releases, but default and static methods on interfaces are only available in Nougat.

 It is also difficult to keep the minimum runtime requirements for version3, but it would still be possible to support API compatibility when run on a modern VM. 

Another problem may be accidental loss of wrapping, but this should be manageable.

Depending on how the wrapping is done, there may also be performance problems.  For example, if the ultimate backing implementation style uses a packed representation, or keeps subclass information attached to class objects where possible, requests for subClassOf axioms might be materialized on demand.  This can be trivial if the materialized axiom is transient, but can use a lot of space if the caller is wrapping and saving every axiom in a set or wrapper (depending on how the materialization is done). Performance characteristics may be unexpected.  This is less of an issue for an initial implementation modeled closely on existing classes.

**Comment by ignazio1977** [comment]
I think it's worth splitting out the discussion on Android support - if we want a core that's Android compatible, it would be best to decide its interface explicitly.

Regarding wrapping, aren't we more broadly describing a new API and an adapter for existing client code? This would simplify the task, as instead of renames and complex migrations we could just design the new API as we like and then change the adapter to match - an activity that would provide a template for a migration guide between old and new API (not unlike what I've done in the past for version 4 and 5, actually, where I took the tests from the previous version, pointed them at the new version and kept track of all that was required to compile and run them).

Speaking of API design, it would be good to discuss general rules about what we want to achieve, so that we have consistency and whatever is the best word to describe lack of surprises - I think it was in the preface to Clean Code that one of the developers asked to provide a definition of clean code said: "code that, when you read it, does not surprise you".
