### ISSUE TITLE
Tags on 4.2

### ISSUE THREAD

**Issue by phillord** [owlcs/owlapi#618]
I think you are missing tags on 4.2.5, 4.2.7 and 4.2.8. Or maybe you didn't push them!

**Comment by ignazio1977** [comment]
Yeah I forget often, I'll get around to it.

**Comment by phillord** [comment]
Happens to me all the time. Why tags don't transfer automatically, I don't know.

**Comment by sesuncedu** [comment]
You can configure git push to automatically push annotated tags

https://git-scm.com/docs/git-config#git-config-pushfollowTags

Of course if you forgot tags, github will use the date of an annotated tag
as the release date, rather than the date of the commit. The date on an
annotated tag can be set by setting an environment variable when calling
git tag.

Simple really.

**Comment by phillord** [comment]
To (mis)quote Arthur Dent, "This is obviously some strange usage of the word 'simple' that I hadn't previously been aware of."

**Comment by ignazio1977** [comment]
Almost no simple thing can be explained in 140 characters or less, unlike complex things.

**Comment by ignazio1977** [comment]
Done. They don't appear in the GitHub view in order, but aside from that...
