### ISSUE TITLE
about IOException Server returned HTTP response code: 403 for URL

### ISSUE THREAD

**Issue by FonyLi** [owlcs/owlapi#619]
Hi there,

I got some URL exception recently.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://wwwxxx.xxx/xxx.rdf

Is it because the particular website we are trying to access is checking the User-Agent HTTP header and denying access to anything that doesn't look like a normal browser, to prevent bots.

It will be checked especially by some websites holding the "imports" of some ontology.

So can you modify this class a little bit?:
owlapi/api/src/main/java/org/semanticweb/owlapi/io/DocumentSources.java

from

HttpURLConnection con = (HttpURLConnection) conn;
con.connect();

to
HttpURLConnection con = (HttpURLConnection) conn;
con.setRequestProperty("User-Agent", "Mozilla/5.0"); // pretending we are a browser.
con.connect();

I'm using 5.0.5 owlapi and rewrite this class and replace the one in the dependency, it is working.

Or do you have some better idea? Thanks.

I didn't find a similar issue in the pool, and please forgive me if it is a known bug.

Cheers,
Tony

**Comment by ignazio1977** [comment]
Pretending to be a browser is ok for this site but not good for others, so it will need to be config driven rather than hardcoded.

Whether the website has a legitimate reason for refusing connections to non browser agents or not is between you and them :-)

An alternative to modifications is to create your own OWLOntologyDocumentSource implementation, set to return an InputStream or a Reader and handling the http connection as you see fit. That should be simple enough and will work with other API versions as well.

**Comment by FonyLi** [comment]
Thanks for you quick reply.
Yeah, create my own OWLOntologyDocumentSource  is a good idea. I'll try that, Thanks again, and I'l close this ticket.

**Comment by sesuncedu** [comment]
Shouldn't use a well known user agent here, but it is probably a good idea
to set one by default.

We didn't make it a requirement in HTTP, but enough sites (e.g Wikimedia)
require it now that it's probably worth doing.
