### ISSUE TITLE
getObjectPropertyDomains + owl:unionOf + external reasoner

### ISSUE THREAD

**Issue by bdecarne** [owlcs/owlapi#626]
Hi,

I try to achieve this goal : for each property of an ontology, i need to find the direct domains named classes :

```java
Set<OWLObjectProperty> props = ontology.getObjectPropertiesInSignature();
for(OWLObjectProperty prop: props) {
    System.out.println(prop);
    for(Node<OWLClass> _class: reasoner.getObjectPropertyDomains(prop, true)) {
        System.out.println(" --> " + _class);
    }
}
```

Some domains are declared as owl:unionOf : 

```
:hasFloorSize rdf:type owl:ObjectProperty ;
              rdfs:domain [ rdf:type owl:Class ;
                            owl:unionOf ( :AccommodationProduct :RoomFeatureSpecification )
                          ] ;
              rdfs:range <http://schema.org/QuantitativeValue> ;
              rdfs:label "a pour superficie au sol"@fr ,
                         "has floor size"@en .
```
I expected to get :AccommodationProduct and :RoomFeatureSpecification as direct domains, but node it's empty :

```
<http://test.com#hasFloorSize>
 --> Node( owl:Thing )
```

But, if i declare owl:intersectionOf, output is ok : 

```
<http://test.com#hasFloorSize>
 --> Node( <http://test.com#AccommodationProduct> )
 --> Node( <http://test.com#RoomFeatureSpecification> )
```

I dont understand this behaviour, but it happens with Hermitt and Pellet... so did u misunderstood the method goal ?

Thx

**Comment by ignazio1977** [comment]
When the domain is an intersection, the reasoner can infer that all individuals having the property belong to all classes listed in the intersection - so it can list the classes you see. It cannot return the intersection itself because OWLReasoner cannot return anonymous expressions - this is a design decision, because if a reasoner is required to return anonymous expressions in queries, it cannot be complete and terminate; the anonymous expressions that are super classes of a given class expression are infinite.

With a union, the reasoner cannot determine which classes /all/ individuals will belong to - it knows some will belong to one expression in the disjunction and some to the other, but it cannot infer a common ground valid for all, except of course owl:Thing, which is what you see (that's not an empty node, it's the top node).

**Comment by sesuncedu** [comment]
[@pfps has different opinions on the semantics of schema.org, and it's mapping to OWL. 
@danbri says that the mapping to union classes is not necessarily wrong, though there are some other assumptions that are needed to lower the level of wrongness - e.g. reasoning on instances must take place using the version of the schema that was in effect at the time that the instance was created (since domains or ranges can be extended over time). As long as domains and ranges aren't narrowed, it is safe to use later versions on older instances, although inferences may be missed. 

The reasoners are behaving as specified (though the specification is questionable). 

The object property domain is 
```AccommodationProduct ∐ RoomFeatureSpecification ```

If we have an assertion that ```x hasFloorSize y``` we *cannot* conclude that x is an AccommodationProduct. Nor can we conclude that x is a RoomFeatureSpecification. It could be one or the other. 

Since the method  ```OWLReasoner::getObjectPropertyDomains``` returns a collection of ```OWLClass``` objects, which correspond to named classes, and there is no OWLClass domains, there are no such values to return. 

owl:Thing is included in the results, because we can always infer that x is a thing. Everything is a thing. 

The more useful set of results would be a list of all the OWLClass's which we can be certain the property can be used on (for different values of certain, and different levels of completeness).

I believe that this is very important feature missing from the current API. 

The problem can be solved in a few different ways, depending on what your goals are. 

Some  are well suited for analyzing the implicit hierarchies in domains and ranges specified as unions. This can be at different levels of granularity. 

Others are suited to finding all the classes to which a property can be applied. This is different from getting the domains, since each entry does not allow one to make inferences about the subject of an assertion using the property. 

In each of these cases, there are different approaches to implementation, based on the granularity of the desired results, and the size of the ontology. 

Criticollab has written  code implementing some of these approaches, for some specific applications and ontologies, including schema.org (a simple approach detected a number of errors and omissions). 
If you have a specific need, contact me and we can sort something out. 

[Hardening and generalizing the code to deal appropriately with different scales of ontologies, and different types of reasoners, *and* making this kind of functionality available in future versions of the API is high on my draft list of features / tasks that would be a compelling part of the nebulous funding plans for the future OWLAPI. 
One thought is to let  features like this, that don't have specific dependencies  be independently sponsored (whether by traditional means, crowd-funding, or some other approach).]

**Comment by ignazio1977** [comment]
> nebulous funding plans for the future OWLAPI.

I'd say. I'm not aware of any form of currency provided to any developer for the purpose of extending said API. Not that my knowledge would influence the existence of such a thing.

**Comment by sesuncedu** [comment]
[That's the nebulousity in a nebula-shell. (You beat my email)]

**Comment by sesuncedu** [comment]
[back almost on-topic] 

Finding the effective range of a property for a specific class is an even harder problem to solve in the general case. Cardinality constraints  become complicated permutations, and data properties have to be wrangled. Hermit has fairly separable data  wrangling on the insides, which is not exactly a surprise :) Some of that might be reusable, though I can't remember if the regular expression processing engine can decompile back to simplified regular expressions 

There's also tge related issue of what additional properties (with what effective ranges) can be added to specific individuals (or relatedly, what properties have had specific values inferred).
