### ISSUE TITLE
Provide an efficient way to test if an ontology contains any entities of a given type in the signature

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#698]
I want an efficient way to determine if an ontology contains individuals (or classes or...).  At the moment I have to use the getXIsSignature methods to do this.

We could have something like

```java
boolean containsIndividualsInSignature()
```
and one method for each type of entity

or

```java
boolean containsEntitiesOfTypeInSignature(EntityType<?> type)
```

**Comment by ignazio1977** [comment]
So, not whether a specific entity is in the signature but whether there's any class in the signature.

Re individuals, would that include anonymous ones? They're not entities but it's one of those things that trips people up. If yes, EntityType as is is not enough.

Adding it in version 4 might cause some third party implementations to moan; in 5 we can get around that with a suboptimal default implementation. Are we happy with that risk? (Not that I think it's too big a risk...)

**Comment by matthewhorridge** [comment]
> So, not whether a specific entity is in the signature but whether there's any (e.g.,) class in the signature.

Precisely.

> Re individuals, would that include anonymous ones? They're not entities but it's one of those things that trips people up. If yes, EntityType as is is not enough.

I'm only bothered about entities.

> Adding it in version 4 might cause some third party implementations to moan; in 5 we can get around that with a suboptimal default implementation. Are we happy with that risk? (Not that I think it's too big a risk...)

Can't we do default methods in 4?  Is there some commitment to pre-Java 8?

**Comment by ignazio1977** [comment]
I seem to remember a discussion to that effect. I don't think we'd see big problems coming out of this, but I'm not sure what the new version number should be, to reflect this kind of change.

**Comment by ignazio1977** [comment]
The consensus so far (The discussion has happened between Matthew and myself) is to move forward the release number to 4.5.0 and keep the changes to minimal additions to interfaces, with default methods - so that existing APIs will need, at worst, a recompile to work.

4.5.0 does not have a specific meaning - ideally we'd have a major version change but 5 was taken. However it allows for more releases in the 4.3 and 4.4 series, which would use Java 7 still,, should the need arise. It does not look very likely - the 4 branch is not seeing many updates, and the majority of them are for Protege visible issues, which is already using Java 8 in its code base. I imagine this to be the case for most other libraries and tools.

What are your thoughts?
