### ISSUE TITLE
DataProperties change when write and read in RDFXMLDocumentFormat

### ISSUE THREAD

**Issue by Galigator** [owlcs/owlapi#706]
In the attach example the '\r' character (of the hard String) is transformed into an '\n'.
Using TurtleDocumentFormat or RDFJsonLDDocumentFormat the character isn't transformed.
Is this the expected behaviour ?

[TestXMLRDF.txt](https://github.com/owlcs/owlapi/files/1384917/TestXMLRDF.txt)

**Comment by Galigator** [comment]
OWLXMLDocumentFormatFactory fail as well. Maybe this is related to XML stuff.

**Comment by ignazio1977** [comment]
Indeed, it's an XML thing as far as I can tell.

Starting from your example, I've written the following test case:

    final static String hardString = ");alpha\"#\\\n \t\n\rbeta<xml></xml>";

    @Test
    public void should() throws ParserConfigurationException, TransformerException {
        Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();
        Element test = doc.createElement("test");
        doc.appendChild(test);
        test.appendChild(doc.createTextNode(hardString));
        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();

        DOMSource source = new DOMSource(doc);
        StringWriter w = new StringWriter();
        StreamResult result = new StreamResult(w);
        transformer.transform(source, result);
        assertEquals(w.toString(), hardString);
    }

This test obviously fails, because it compares the whole XML output to your original string, but if you check the comparison you'll see the \r character is turned into a \n.

That string is peculiar in itself, though, because in Windows a return sequence is \r\n not \n\r. So was the intent of the original writer to have two carriage returns or just one? If just one, then the problem is that that's just the wrong input. If two, then I'd recommend to choose one representation or the other, not to mix line delimiters :-)

**Comment by ignazio1977** [comment]
Found it in the XML specs: \r characters are turned in \n characters, and \r\n sequences in \n characters.

https://www.w3.org/TR/xml/#sec-line-ends

> To simplify the tasks of applications, the XML processor must behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating both the two-character sequence #xD #xA and any #xD that is not followed by #xA to a single #xA character.

If you wish to preserve the \r, and an XML format is involved, \r needs to be escaped before the literal is created (as things stand).

I'm not sure whether users would wish for the RDF/XML writer to escape it for them. I can see arguments either way.

**Comment by Galigator** [comment]
Thank you Ignazio for your fast and precise answer.

It is always a surprise when a unit test fail because of changes in serialization factory.
But, I think it is better to let it as it is.
Standard is better, even when counter intuitive.
As far as I have test Jena have the same behaviour on rdf/xml.
