### ISSUE TITLE
owlapi5/HermiT: Subclasses omitted

### ISSUE THREAD

**Issue by enp0s1** [owlcs/owlapi#713]
Hello everyone,

first of all I would like to apologize if I am not using correct terminology. I am still pretty new to ontologies and still in the learning phase.

I am currently building a vue.js web application to visualize Ontologies (similar to Protege, so a class hierarchy view) in a web browser. In order to get an RDF/XML-formatted Ontology into something that a browser can understand, I am using the following code to parse my Ontology into a super primitive JSON-hierarchy (using owlapi5 and HermiT):

(Code shortened as my internal data structure seems to be somewhat irrlevant to my question.)

```
public void ontologyToJSON() {
    ontology = manager.loadOntologyFromOntologyDocument(input);
    reasoner = new Reasoner.ReasonerFactory().createReasoner(ontology);

    Node<OWLClass> root = reasoner.getTopClassNode();
    traverse(root);
}

public void traverse(Node<OwlClass> clazz) {
    if (newRoot.getRepresentativeElement().isOWLNothing() || newRoot == null) {
        return;
    }

    NodeSet<OWLClass> children = reasoner.getSubClasses(newRoot.getRepresentativeElement(), true);

    for (Node<OWLClass> child: children) {
        OWLClass representativeClass = child.getRepresentativeElement();
        System.out.println(representativeClass);
        traverse(child);
    }
}
```

Here is the Ontology I am trying to process:
```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#"
     xml:base="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5"/>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    


    <!-- http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#ClassX -->

    <owl:Class rdf:about="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#ClassX"/>
    


    <!-- http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#ClassY -->

    <owl:Class rdf:about="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#ClassY">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/enp0s1/ontologies/2017/10/untitled-ontology-5#ClassX"/>
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
    </owl:Class>
</rdf:RDF>



<!-- Generated by the OWL API (version 4.2.8.20170104-2310) https://github.com/owlcs/owlapi -->
```

Here's the class hierarchy rendered through Protégé:
![OntologyProtege](https://i.imgur.com/XhPDOih.png)

ClassY is a subClass of owl:Thing, as well as a subClass of ClassX. However, my code leads to the following result:

```
owl:Thing
-- ClassX
---- ClassY
```

The fact that ClassY is a direct subclass of owl:Thing seems to be omitted. Am I misunderstanding something here? My desired output would be:

```
owl:Thing
-- ClassX
---- ClassY
-- ClassY
```
Is there a way to achieve this?

Thank you very much in advance.

EDIT: It appears that I cannot set the "question"-Label myself. Apologies for the inconvenience.

**Comment by ignazio1977** [comment]
The problem here is that Y is *not* a direct subclass of `Thing`. The fact that there is an explicit axiom saying it is a subclass of `Thing` does nothing to make it a direct subclass. `A` is a direct subclass of `B` only if `A` is a subclass of `B` and there is no named class `C` so that `A` is a subclass of `C` and `C` is a subclass of `B`. In your case, `X` plays the part of `C` and stops `Y` being a direct subclass.

What Protege is doing there is providing both asserted and inferred hierarchy in the same view; you could replicate this by creating two hierarchies, one as you have already implemented, with a reasoner, and one that is only based on subclass axioms in the ontology.

For that, you'd start with all the classes in the signature and select those that appear in a subclass axiom as asserted subclasses of Thing, as well as the ones that do not appear as subjects of any subclass axiom (these are implicitly 'direct' subclasses of Thing, in the asserted hierarchy. Thse will be the classes one level below Thing. then, for each class, repeat the process, visiting the graph defined by the subclass axioms.

Alternatively, you can create the second view using the StructuralReasoner in OWLAPI; this reasoner does no inference and uses only the asserted axioms. As it implements the same `OWLReasoner` interface as HermiT, you can reuse the same code you've already written to generate the hierarchy, then merge the two trees together starting at the root.

**Comment by enp0s1** [comment]
Thank you so much, this helped a lot.
