### ISSUE TITLE
OWLOntology with shared structure causes incorrect RDF/XML

### ISSUE THREAD

**Issue by rctauber** [owlcs/owlapi#780]
We are trying to update ROBOT from 4.2.6 to 4.5.4. When doing so, everything built properly, but one of our integration tests failed.

When running [relax](http://robot.obolibrary.org/relax) on [ribosome.owl](https://github.com/ontodev/robot/blob/master/docs/examples/ribosome.owl) (Manchester syntax), the output contains the following:
```
<rdfs:subClassOf rdf:parseType="Collection">
    <owl:Restriction>
        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0043226"/>
    </owl:Restriction>
</rdfs:subClassOf>
```

the `rdf:parseType="Collection"` only shows up on the first listed entity - and causes an error when opening in Protege. I removed that entity from the input and ran `relax` again, and the `rdf:parseType` just shows up on the next one.

The weird part is that if I convert `ribosome.owl` into a different syntax, it works properly. I also tried producing the output in a different format, and this works fine as well.

This first appears in 4.2.8, but I couldn't identify any changes that would cause this. It may be an issue with our test data or the [RelaxOperation](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/RelaxOperation.java) itself, but we've never had a problem with this before.

Thank you!

**Comment by ignazio1977** [comment]
The input has an EquivalentTo in place of this subClassOf; in RDF the equivalence would use a collection for the list, while a subClassOf would not. I'm guessing something is falling off the tracks there.

**Comment by ignazio1977** [comment]
I might be reading the input wrong though (commenting from my phone)

**Comment by rctauber** [comment]
The relax command takes the equivalent classes axioms and turns them into subclass axioms, so it's behaving properly except for the addition of the `rdf:parseType`. The `rdf:parseType="Collection"` is there (and should be) for the original equivalent classes axiom. I'm not sure why it's being appended to the *first* subClassOf axiom...

**Comment by ignazio1977** [comment]
Ah I see... I think it's going to the first axiom because in the triple transformation the parseType attribute would only exist on the list. For different input syntaxes, the RDF artifacts do not exist.

Not sure what's changed between versions to trigger this. There have been many bug fixes in that area, but I can't place them from memory - it's possible one of them triggered this, or a new bug was introduced.

**Comment by ignazio1977** [comment]
From the release notes, issue #564, #574 and #586 might all have something to do with this problem.

**Comment by rctauber** [comment]
Looks like the change was introduced with 62525de. Removing [this line](https://github.com/owlcs/owlapi/commit/62525dea78b5c4e4951b1bedc6f7f9e54e5bd109#diff-bf73df4165c32ca98ec018229948beeaR223) solves the problem.

**Comment by ignazio1977** [comment]
Surprising, and good catch.

I remember that change, and at the time it was necessary to remove bugs. Yet, if I comment out all uses of the remapping, no tests fail - I have to guess some other fix is doing the required work. RDF/XML makes my head hurt, even after years of maintaining this code.

**Comment by rctauber** [comment]
Thanks!

Do you think any fix can be implemented for this? We'd like to bump up our OWLAPI version for the next ROBOT release.

**Comment by ignazio1977** [comment]
It needs a fix but I'd like to figure out exactly what's happening before doing that, in case this reopens other issues.

**Comment by jamesaoverton** [comment]
Thanks @ignazio1977. This bug has been a bit of a mystery to us, but that explanation makes sense. We’re happy to tweak the ROBOT code.

**Comment by ignazio1977** [comment]
There are basically three logical axioms created in the Relax rule (I'm using only one of the original equivalent axioms for simplicity):

    SubClassOf(<http://purl.obolibrary.org/obo/GO_0044464> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/GO_0005623>))
    SubClassOf(<http://purl.obolibrary.org/obo/GO_0044464> <http://purl.obolibrary.org/obo/GO_0005575>)
    EquivalentClasses(<http://purl.obolibrary.org/obo/GO_0044464> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/GO_0005575> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/GO_0005623>)) )

But when attempting to save this ontology in an OWLAPI test, the output is correct. Really puzzling.

**Comment by rctauber** [comment]
Thanks for looking into this. I only ran into the issue when running `relax` on the Manchester syntax input. It's very strange.

**Comment by ignazio1977** [comment]
Right, I'll see if starting from man syntax input changes my test.

**Comment by ignazio1977** [comment]
I've tried the same input and copied the code from the Relax operation to my test, and yet I can't replicate the problem. Looks like the same code, running in different projects, is behaving differently. This is getting fun, I'm this close to start blaming the compiler.

**Comment by ignazio1977** [comment]
I managed to replicate this by accident.

Failing test:
- Load ontology
- relax ontology
- save ontology
= bad output

Successful test:
- Load ontology
- save ontology
- relax ontology
- save ontology
= good output

I've tried doing the same in the Robot code, but it does not work there.
It looks like there's some effect linked to static members.

**Comment by ignazio1977** [comment]
I'm starting to make some progress.

These are the triples being written out:

        <GO_0044464> <subClassOf> <GO_0005575>.
        <GO_0044464> <subClassOf> _:genid3.
        <GO_0044464> <equivalentClass> _:genid1.
        _:genid1 <#type> <Class>.
        _:genid1 <intersectionOf> _:genid4.
        _:genid4 <#type> <#List>.
        _:genid4 <#first> <GO_0005575>.
        _:genid4 <#rest> _:genid2.
        _:genid2 <#type> <#List>.
        _:genid2 <#first> _:genid3.
        _:genid3 <someValuesFrom> <GO_0005623>.
        _:genid3 <onProperty> <BFO_0000050>.
        _:genid3 <#type> <Restriction>.
        <GO_0044464> <#type> <Class>.
        _:genid2 <#rest> <#nil>.


`_:genid3` is where things go wrong. The remapping method @rctauber pinpointed earlier is remapping it incorrectly - it's redirecting to `_genid2`, i.e., the blank node that links together the intersection list of arguments. This makes the renderer think it needs to write out a list of one element, and that's where the wrong attribute is coming from.

**Comment by ignazio1977** [comment]
The remapping is correct, what's wrong is the id used for remapping. There are two counters for ids for remapping nodes, one that's local to the renderer (allowing output of ids that start on 1 for each ontology output, and allowing the output from multiple saves to be identical, including any explicit blank node ids where required) and one that's static in NodeID, and allows adding anonymous individuals without clashes between separate ontologies.

What's happening here is a clash - the ontology has anonymous nodes between 1 and 4, and the shared structure at node 3 means the node must be remapped to two nodes for correct RDF output. But, this remapping starts at 1, and it creates nodes 1 and 2 - which clash with the ids just created.

Only happens when there's remapping /and/ the ontology nodes have very small ids - that's why my tests were giving unreliable results. If there are multiple ontologies being loaded and saved, the NodeID counter goes up - so, when writing the ontology happens, clashes only happen on the first ontology loaded and saved. This also means that the test revealing the defect only does so when running by itself. Running together with the other tests, it passes without a glitch. VERY confusing.

Problem for the fix: we cannot switch to one static counter, because this stops the ability to have identical outputs from two saves of the same ontology (when node ids have to be written out explicitly, e.g, axiom annotations or anonymous individuals used in multiple axioms). We cannot have ontology level counters, because that allows for clashes to happen between ontologies - so that an axiom created with an anonymous individual cannot freely be moved across ontologies, thus breaking a design constraint that underpins many existing systems - Protege, various reasoners, and so on. And we cannot switch to GUIDs for the nodes because this removes clashes but it removes the like for like output when doing multiple saves (GUIDs are also more expensive than a counter).

The best solution I can think of is to offset the static counter. The NodeID counter is an atomic long, while the local ones are integers - so starting the NodeID at Integer.MAX_VALUE means that ontologies can have a lot of locally explicit node ids without clashing with non remapped values. Not very elegant, but seems to hold up.

**Comment by ignazio1977** [comment]
Release 4.5.5 and 5.1.7 include the fix.

**Comment by rctauber** [comment]
Great, thanks so much!

**Comment by jamesaoverton** [comment]
Amazing detective work @ignazio1977! Much appreciated.
