### ISSUE TITLE
Empty Ontology when combining langString and URIs with quotes

### ISSUE THREAD

**Issue by sven-h** [owlcs/owlapi#787]
Hi,

I have some problems loading an ontology when it contains a weird URI (e.g. containing quotes) together with a statement which uses rdf:langString as a datatype.
A minimal working example is attached: 
[minimal_example.xml.txt](https://github.com/owlcs/owlapi/files/2379241/minimal_example.xml.txt)

In such a case the parser finishes without any complains (also no log entries - neither error nor info)
but the ontology contains 0 axioms and 0 logical axioms.

I first thought this is an issue with parsing quotes but this isn't the case.
If one replaces the datatype langString to "http://www.w3.org/2001/XMLSchema#string" the quotes are parsed correctly.
I realized that the parser returns with an empty ontology if it encounters anywhere in the file a langString datatype and somewhere else a weird URI.

Best regards
Sven

**Comment by ignazio1977** [comment]
This could be an issue where one of the parsers is misbehaving - it is not finding anything to parse but it is also not throwing an exception, so the ontology manager thinks parsing has actually completed successfully.

Can you add which OWLAPI version you're using and what is the format returned by `manager.getOntologyformat(ontology)` where `ontology` is the empty ontology resulting from this load?

**Comment by sven-h** [comment]
The used OWL API version is 5.1.7.
I realized that it chooses the "TriX"parser when rdf:langString is contained ("RDF/XML" otherwise).
Attached a [working maven example](https://github.com/owlcs/owlapi/files/2383244/maven_example.zip) .
Maybe when choosing the parser the XML/RDF one can't parse it correctly and thus selecting TriX?

**Comment by ignazio1977** [comment]
Yes the TriX parser has this annoying behaviour. It's possible to ban a parser - I'll paste an example later.
langString is an oddball: introduced after the rdf/XML spec to mark literals that are strings with a language tag, which is no different from a plain literal with language tag. All string literals work without an explicit type, since the right one can always be figured out, although with pain. So, in general, langString does not need to appear in the XML data. Not sure off the top of my head if it's meant to be parsed of present.
