### ISSUE TITLE
Cyclic import of versioned ontologies fails

### ISSUE THREAD

**Issue by kartgk** [owlcs/owlapi#788]
This is my code

            OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
            OWLOntologyLoaderConfiguration loadingConfig = new OWLOntologyLoaderConfiguration();
            loadingConfig = loadingConfig.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);
            OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new FileDocumentSource(new File("***FundEntities.rdf")), loadingConfig);

Attaching the Ontology file

[FundEntities.txt](https://github.com/owlcs/owlapi/files/2385395/FundEntities.txt)

It fails with below exception, unable to figure out whats wrong, pls guide.

    11:02:01,071  WARN main util.SAXParsers:95 - entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl, error message: Property 'entityExpansionLimit' is not recognized.
    org.semanticweb.owlapi.model.UnknownOWLOntologyException: Unknown ontology: OntologyID(OntologyIRI(<https://spec.edmcouncil.org/fibo/ontology/BE/FunctionalEntitiesExt/SPVs/>) VersionIRI(<null>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.directImports(OWLOntologyManagerImpl.java:483)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.getImportsClosure(OWLOntologyManagerImpl.java:545)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1719)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.importsClosure(OWLOntologyManagerImpl.java:527)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.importsClosure(OWLImmutableOntologyImpl.java:447)
	at org.semanticweb.owlapi.model.parameters.Imports$1.stream(Imports.java:33)
	at org.semanticweb.owlapi.model.OWLSignature.annotationPropertiesInSignature(OWLSignature.java:222)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.annotationPropertiesInSignature(ConcurrentOWLOntologyImpl.java:2759)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.importsClosureChanged(OWLRDFConsumer.java:680)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1442)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:989)
	at widoco.TestOwlAPI.main(TestOwlAPI.java:21)

**Comment by ignazio1977** [comment]
It's a bug - the imported ontology has a nonnull version, but when reviewing the imports closure an ontology with no version is getting used (and not found, obviously).

Your code is correct in setting the missing imports directive, but here the problem happens outside of the imports loading, so those settings have no effect.

**Comment by kartgk** [comment]
Thanks for investigating.

**Comment by ignazio1977** [comment]
The same ontology file is loaded through two different URLs here:

    https://spec.edmcouncil.org/fibo/ontology/BE/FunctionalEntitiesExt/SPVs/
    https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/FunctionalEntitiesExt/SPVs/

This scenario is allowed, however there is a problem with version IRIs, because they are parsed at the end of the RDF/XML parsing. So, ontology X is loaded, then ontology Y is loaded, the version is found and set, and at this point the id for ontology Y has IRI and version IRI. However Ontology X still has no version triple parsed. When an imports closure refresh is called at this point, the two ontologies are known to be synonyms of each other but the ID objects differ (the version for the second one will be updated later). However, at this point the ID is not found in the indexes of the manager, and this causes the exception. 

No remote import has failed to be downloaded and parsed - that part of the code is working fine. What's not working fine is the id update with the version during the parsing; that code does not take into account the possibility of the same content parsed from two different IRIs. Unfortunately in OWL one can specify an import but not a version, so there is no way of building the correct id ahead of time.

Workaround: use the same URL in your current ontology, or, if you cannot modify the data, use an OWLOntologyIRIMapper to map one URL to the other - this will trick the code because there will be only one remote URL to resolve and only one ID to update. This should work while I figure out a good general solution.

**Comment by ignazio1977** [comment]
Root issue is that the ontology id is composed of two triples, and the parsing was using the ontology id of the ontology being parsed as temporary storage for the data as it came in from the XML parser. However, the ontology at that point is already indexed by id in the manager, and the id changes confuse the requirements on the manager. Recursive imports like the one in this situation mean that one ontology gets kicked out of the manager indexes, while the ontology object still holds a manager reference.

A better approach is to collect ontology IRI and version IRI in a separate storage area - which in this case already existed for the ontology IRI, as an ontology file can contain more than one ontology declaration (in itself a source of different headaches).

This solution has the added advantage of making the load process more resilient to conflicting imports - when two different versions of the same ontology are in the same imports closure. Previously, the order in which the imports were found would determine which ontology was actually loaded, and it would be possible for the loaded ontology to have the wrong version with respect to its content; also, the other ontology would not be visible. This made it harder to diagnose that a conflict was occurring. Now all ontologies will appear in the manager, and, while this does not solve the conflict issues, it will allow to list all ontologies loaded. Detecting a conflict becomes then much simpler.

**Comment by ignazio1977** [comment]
This commit fixes the code bug in OWL API, however there is still a failure loading this test ontology. This depends on the cyclic nature of the import, and the fact that it cannot be determined ahead of time that the two instances of the ontology have the same exact content. In parsing with the different direct imports available, the parser has different declarations available, and some are missing, meaning the two data streams parse to different ontologies - some properties are turned to annotation properties. This might require a fix to the ontology to be sorted.

**Comment by ignazio1977** [comment]
I take that back, some of the annotations should have been parsed and are being missed.

**Comment by ignazio1977** [comment]
The annotation axioms missing were due to bad placement of the ontology ID creation. I'll fix that in the next commit.

However, there is also `hasMaturityLevel`, which is used to annotate the ontology. This property is declared as `ObjectProperty` in `https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Utilities/AnnotationVocabulary/`, and the parsing order means this declaration is found and used in one ontology but not the other. This causes punning - the ontology IRI is assumed to be an individual IRI, and an object assertion axiom is created. This punning is illegal in OWL 2 DL. I assume the property was meant to be an annotation property, so this needs to be fixed in the data.

If that's not possible, my original workaround of using OWLOntologyIRIMapper objects remains the only approach that can fix the loading without data changes.

**Comment by ignazio1977** [comment]
The fix will be available in the next release; in the meantime you can check out the source and build it yourself.

**Comment by jgeluk** [comment]
>However, there is also hasMaturityLevel, which is used to annotate the ontology. This property is declared as ObjectProperty in https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Utilities/AnnotationVocabulary/, and the parsing order means this declaration is found and used in one ontology but not the other. This causes punning - the ontology IRI is assumed to be an individual IRI, and an object assertion axiom is created. This punning is illegal in OWL 2 DL. I assume the property was meant to be an annotation property, so this needs to be fixed in the data.

>If that's not possible, my original workaround of using OWLOntologyIRIMapper objects remains the only approach that can fix the loading without data changes.

Very good catch! We will fix that. @dallemang @rivettp
