### ISSUE TITLE
IRI PREFIX_CACHE instance can use too much memory in version 4.5.x

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#825]
The caffeine cache is built using soft keys, where equality is based on identity.  On long runs, with tens of thousands of ontologies, this can consume huge amounts of memory.  (At lest I think this is what's going on)

I've noticed that version 5 changes the cache to have a maximum size (no soft keys or soft values).  Please can this be backported to version 4?

**Comment by matthewhorridge** [comment]
p.s. same for OWLDataFactoryInternals

I meant weak keys above btw.

**Comment by ignazio1977** [comment]
As discussed in chat: the problem is lack of a max size on the caches. There are a few of these caches around, some with and some without max size. I'll uniform the behaviour and add some configuration options.

**Comment by ignazio1977** [comment]
Included in release 4.5.10

**Comment by sszuev** [comment]
I'm sorry for disturbing you (especially since the issue is already closed), but could you explain why this IRI namespace cache is needed at all?
A Java String usually is already cached (string pool). 
There is also a method `String#intern()` to perform operation `x -> x` , for manual pool control and to put missed Strings into it.
Also, there are a large number of other similar implementations, including java.net.URI, jena IRI, etc, noone contains a special cache for namespaces (correct me if I am mistaken). 

Moreover, this cache is the only place of using external lib (caffeine) in owlapi-api.
I think it would be better if this module (owlapi-api) would not rely on any dependencies (with exception of slf4 maybe).

**Comment by ignazio1977** [comment]
Well behaved string caches are a recent innovation in Java, this code needs to run on java 8 and there we still see an advantage to caching the namespaces. Iri objects are cached in the parsers.

Removing the dependency from API is a good call but requires interface changes (IRI cannot have a factory method, not unless we do something really clever). In version 6 we're doing just that.

**Comment by sszuev** [comment]
I'm talking just about just IRI PREFIX_CACHE, not changing in interfaces, factory methods, etc. 
String.intern() existis starting Java 6, and yes, it is becoming better from version to version. See http://java-performance.info/string-intern-in-java-6-7-8/ 

No interface changes is needed: just remove `private static final LoadingCache<String, String> CACHE` field and replce `namespace = CACHE.get(prefix);` with `namespace = prefix.intern()`. Or nor replace, if benchmarks will show it is better. There is no other usages of Caffeine in OWL-API-**api**.

**Comment by ignazio1977** [comment]
:-) yes I read that article a few years ago.

Problem is that we tried `String.intern` and it didn't work reliably. As it varies by quite an amount in behaviour according to the VM that runs the code, and that tends to generate all sorts of difficult to diagnose bug reports. Caffeine adds a dependency but removes that uncertainty.

If the matter was about adding a new dependency, I wouldn't add the dependency. But in this case it's already there, has been for a number of versions, and therefore developers have already worked around this issue, if they found it a problem. So, removing the dependency in this version, considering that it's still part of the dependencies needed by the default implementation, offers very little actual improvement.

Is there a context where the improvement is much bigger, such as systems using a different impl module?

**Comment by sszuev** [comment]
> Is there a context where the improvement is much bigger, such as systems using a different impl module?

Well, yes. 
At least my ([ONT-API](https://github.com/avicomp/ont-api)), although it is not quite a module.
It does not dependent on default OWL-API impl, and it is used in several different projects, including editor with its ecosystem.
It is a little bit wrong example - the project itself also uses Caffeine (and currently I am quite satisfied with it). 
So, right now it is not a real problem, but rather a sign of a problem or some misunderstanding.
Also, if there is some extra costs involving by Caffeine in the IRI constructor - currently, they are not sensitive enough since there are a lot of other places which requires more attention.
