### ISSUE TITLE
Add support to load an ontology from classpath

### ISSUE THREAD

**Issue by Nyamiou** [owlcs/owlapi#837]
Right now it's possible to use the following schemes when loading imports (taken from OWLOntologyFactoryImpl):
 * "http"
 * "https"
 * "file"
 * "ftp"
 * "jar"

It would be useful if a new scheme "classpath" was added allowing to refer to files inside dependencies without having to provide the path to the JAR itself.

**Comment by ignazio1977** [comment]
Rather than creating a new scheme (there's an iter to get it added to the IANA list of known UI schemes - otherwise it remains as a library specific trick, which I'm not that keen on), we could modify the implementation for the `jar` protocol to make the jar file name optional, e.g.,

`jar:!resource/path/in/jar`

which would be implemented by looking up `/resource/path/in/jar` as a classpath resource.

Note that both this solution and the proposed `classpath` scheme cannot account for the possibiity that the classpath has multiple entries for a certain resource name; multiple files or multiple folders could contain files with the same relative name. This is what already happens with meta-inf/services files - to take into account identically named files, it's necessary to iterate through all the resources with the same name, but for ontologies this process does not have an equivalent; I'm guessing we should warn that the file name is not unique. Silently opening the first file found might cause difficult to replicate bugs.
