### ISSUE TITLE
Unnecessary dc prefix added by Manchester syntax parser

### ISSUE THREAD

**Issue by IvanoBilenchi** [owlcs/owlapi#845]
Hey there!

Is there any reason why the Manchester syntax parser always inserts the Dublin Core prefix in the parsed ontology?

I believe the behaviour is triggered by this line:

https://github.com/owlcs/owlapi/blob/b6cf6d83f42609a9cd7fe5c2f594c603f1406355/parsers/src/main/java/org/semanticweb/owlapi/manchestersyntax/parser/ManchesterOWLSyntaxParserImpl.java#L256

I found this out since I need to retrieve all the (non builtin) prefixes used in a given ontology. Everything looks fine for other syntaxes, though Manchester syntax ontologies have to be corner-cased in client code due to this.

This happens in the latest OWL API 5 version, of course.

**Comment by ignazio1977** [comment]
Seems to be historical - it's been there since the first version of the parser - but I can't find any comment as to why that was chosen.

I can fix that, but just a warning: I'm not sure of the context of your task, but ontologies are under no obligation to declare prefixes for namespaces that the entities mentioned in the ontology use - so it's possible, and quite common as far as I'm aware, to use entities from a variety of namespaces without any prefixes being declared.

**Comment by IvanoBilenchi** [comment]
Thank you for the follow-up. And sure thing, though my specific task involves looking for the non-builtin prefixes that have been declared in the original ontology (I'm not interested in the other namespaces).

It's not a big issue, really, though it's inconsistent with the behaviour of the other parsers. A fix would be appreciated, mainly because it's tricky to workaround without ugly hacks 😅
