### ISSUE TITLE
Javadoc on applyChange/applyChanges and using the wrong manager

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#868]
Several manager's methods, such as `applyChange`, `saveOntology`,  can handle also ontologies, that do not actually belong to the manager.
The javadoc for the method `applyChange` says:

> A convenience method that applies just one change to an ontology that is  managed by this manager

So, this method should not handle any external ontology, correct?
But currently (v5.1.11), it is possible:

            OWLOntologyManager m1 = OWLManager.createOWLOntologyManager();
            OWLOntologyManager m2 = OWLManager.createOWLOntologyManager();
            OWLDataFactory df = m2.getOWLDataFactory();

            OWLOntology o = m1.createOntology();

            OWLAxiom a = df.getOWLDeclarationAxiom(df.getOWLClass("X"));
            m2.applyChange(new AddAxiom(o, a));
            o.axioms().forEach(System.out::println);   

So, we get `m1` changed, while work with `m2`.

**Comment by ignazio1977** [comment]
It depends on the change - axioms added or removed never impact the data the manager is holding, and so any manager will do as far as the ontology is concerned. However, changes that alter the ontology id alter data that the manager is also tracking; using the wrong manager means data will get out of sync.

Also, different managers might hold different listeners that get triggered on ontology changes. In this case, using a different manager will cause different behaviours. Similar considerations apply to adding imports.

Admittedly, it's not the clearest javadoc or the simplest design for this feature...

**Comment by sszuev** [comment]
When I said 'the manager state', obviously, I meant the axiomatic data too - when you add or remove axiom, other ontologies might also be affected implicitly, and it is also possible having the same raw data for two different managers, containing different ontology-views.

Anyways, the current behavior may lead to strange bugs - when client mistakenly uses the wrong manager, and, I think, at least the documentation for these methods might be updated to remove the responsibility for boundary cases of this kind.

**Comment by ignazio1977** [comment]
I agree that the current javadoc is not clear enough. However, if the scenario you're describing with 'raw data, different views' is about the same ontology loaded independently in two managers, it was never a constraint that a change made via one manager should be noticed and visible to another manager; such a behaviour can be added if needed, via a listener, but as far as I know no one has implemented this scenario.

Agreed that it would be better to change how this works, so that changes go through the classes that actually need to know about them. In version 6, the ontology applies the changes. It would be a good idea to remove  the methods from the manager, so the source of the issue disappears.
