### ISSUE TITLE
Ignore OntologyAlreadyExistsException

### ISSUE THREAD

**Issue by billdyla** [owlcs/owlapi#870]
I’m getting the ontology already exists exception during load

How can I ignore this?

Other info:
I’m using missing import strategy of silent
And using a custom loader listener to remap IRIs to  load some ontologies from a triple store
The ontology that that causes the exception is remapped to the triplestore and has a version iri of null

**Comment by ignazio1977** [comment]
Is the ontology being remapped also available at a URL on the web?

What I believe is happening here is that you're remapping one URL to the triple store but the import declarations in the imports closure also include a different URL for the same ontology, but with another version or simply with different contents.

It's not possible to ignore this exception; the fix is, I think, to find which URL needs remapping and to add them to the mapper you're already using.

It would help to be able to see the ontology causing this issue; if that's not possible, the imports declarations of this ontology, and the imports declarations of the ontology closure, might help. There's a known issue on cyclic imports, where missing declarations might cause a similar error, but I can't tell if this is relevant in this case.

**Comment by billdyla** [comment]
Thank you for your help.
That seems to be the problem. 

I have a set of ontologies called core-o of terms; used and imported in many other ontologies. Core-o then imports w3c PROV, DCAT and others. Some of the ontologies cross-import (see example at bottom). Most of the ontologies (except w3) including core-o are stored in the triplestore but also _may be_ web addressable. 

At run-time a list of main/outer ontologies is generated based on user context. Basically, the system is loading and merging a set of main/outer ontologies at run-time, running a reasoner and presenting information, and allowing dlqueries based on the class hierarchy across the loaded ontologies. The system has to _guess_ if the outer ontology should be loaded from the web or from the triplestore. Imports are loaded based on a run-time Mapper (java class) looking for urn: and *core-o* to load from the triplestore.

It is likely the problem occurred when the system generated a list of ontologies included core-o (as a sort of outer/main ontology). During load, imported core-o from the triplestore, but then tried to load core-o from the web, but I’m not able to replicate the problem (as the exception was found in the system logs without enough context to recreate it).

Thanks again; tough problem to debug in a run-time system. I’ve put in a patch to look for core-o ontologies and load from the triplestore; it seems to have been resolved, but maybe the user is on summer holiday.

The below example is not necessarily the problem case, but rather exists in the data.
-bd


Example
—  ontology one ; accessible in triplestore but also possibly web
<http://.../one> a owl:Ontology ;
    owl:imports <urn:two>, <http://…./core-o> .

— ontology two; not web addressable with urn protocol
<urn:two> a owl:Ontology ;
    owl:imports <http://.../one> <http://…./core-o <http://%EF%BF%BD./core-o>> .

— core terms; web and triplestore load-able
<http://…./core-o <http://%EF%BF%BD./core-o>> a owl:Ontology ;
     owl:imports <http://www.w3.org/ns/prov.owl <http://www.w3.org/ns/prov.owl>>  .
