### ISSUE TITLE
OWLObjectPropertyExpression#getSimplified() used incorrectly

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#882]
No overrides for this method in `OWLObjectInverseOfImpl`,  `OWLObjectPropertyImpl` and `OWLObjectImpl` (checked v5.1.11).
That looks suspicious.

So, currently `simp(p) != simp(pe)`, where `pe = inv(p)`
and, for example, the code in the method `SWRLObjectPropertyAtom#getSimplified()` is out of use, because `p`  is always `simp(p)`

**Comment by ignazio1977** [comment]
The code in `SWRLObjectPropertyAtom looks wrong, it should check if the predicate is anonymous and work out what to do from that.

**Comment by ignazio1977** [comment]
The `getSimplified()` method was modified in 2015 #430 as we realised the specs were stopping the creation of expressions like `inv(inv(p))` (the structural definition only allows object property as argument to `inv`, so double wrapping of a property is not a legal construct and wrapping of an object property expression is only valid if the object property expression is a plain object property). With those constraints in place, the only kind of object property expression that can be created is one that is already in its simplest form.

There was some discussion at the time because it appears the restriction is counterintuitive, especially given that double wrapping of properties with the inverse operator is such a common occurrence in textbooks. There's a mention that double wrapping was allowed in some initial draft of the specs and disallowed later; I haven't dug in the details.

However the code in SWRL appears to be relying on an assumption that's no longer correct.
