### ISSUE TITLE
Race condition in Injector

### ISSUE THREAD

**Issue by Locke** [owlcs/owlapi#883]
There seems to be a race condition within the creation of OWLManager instances, which makes the list of ontology parsers different in some instances, leading to some managers with only a single parser (which of course fails).

Basically I am calling this code concurrently from multiple threads:
```
final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();
OWLOntology ont = manager.loadOntologyFromOntologyDocument(ontologyFile.openStream());
```

It took me a while to condense this into a minimal working example, and it unfortunately still requires some luck to trigger. I uploaded the project here: https://github.com/Locke/owlapi-racecondition Best you put a breakpoint on line 76 `logger.error("loadOntologyFromOntologyDocument failed", e)` and give it some tries. On my current laptop with an Intel(R) Core(TM) i7-6820HQ (quadcore + HT) I have to run the main method two or three times to trigger it.

In the unit tests of my actual application the number of parsers, when trigged, is mostly one and I get this stacktrace (OWL API 5.1.11):

```
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing inputstream:ontology32441459793404
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory@3bf24493


Detailed logs:
--------------------------------------------------------------------------------
Parser: org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory@3bf24493
  Stack trace:
org.eclipse.rdf4j.rio.RDFParseException: File does not contain a binary RDF document        org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:138)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1027)
      de.tkip.sbpm.parser.owl.package$.preloadOntologies(package.scala:32)
      de.tkip.sbpm.parser.owl.OWLProcessWriter.<init>(OWLProcessWriter.scala:34)
      de.tkip.sbpm.parser.owl.TestMapper.$anonfun$new$3(TestMapper.scala:31)
      de.tkip.sbpm.parser.owl.TestMapper.$anonfun$new$3$adapted(TestMapper.scala:30)
File does not contain a binary RDF document        org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:403)
      org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:388)
      org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:755)
      org.eclipse.rdf4j.rio.binary.BinaryRDFParser.parse(BinaryRDFParser.java:79)
      org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:182)
      org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:125)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
      uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:235)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1027)
```

Interestingly, I also had this stacktrace, but only a single time:
```
java.util.ConcurrentModificationException:
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1660)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:206)
at org.semanticweb.owlapi.apibinding.OWLManager.createConcurrentOWLOntologyManager(OWLManager.java:128)
```

**Comment by ignazio1977** [comment]
Hi, 've tried your code but no luck triggering the defect.

Cn you add a couple more details? OS and Java version?

**Comment by Locke** [comment]
It happens on both my laptop [1, 2] and desktop PC [3].

I just increased the number of threads and tasks, this seems to trigger it more reliably on my desktop. Please note that the stacktrace will only be logged and not crash the application. I just reduced the logging level so that this can be seen better.

[1] Dell Latitude E5470 Intel(R) Core(TM) i7-6820HQ CPU with HT enabled, Windows 10 1903 18362.388
Native within IntelliJ IDEA with AdoptOpenJDK 11.0.4.11-hotspot

[2] Within WSL via maven exec:java on [1]: Ubuntu 18.04.3 LTS, Kernel 4.4.0-18362-Microsoft with OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

[3] Debian 10 Intel(R) Core(TM) i7 CPU 860 with HT enabled, Linux kernel 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1deb10u1, mixed mode, sharing)
Observable both with maven exec:java and within IntelliJ IDEA

**Comment by ignazio1977** [comment]
No success in replicating the issue but I got something else interesting to happen reliably.

The root of the problem is an unexpected number of parsers available to the manager, so I've reduced the test to just checking how many parsers are registered in the manager; increasing parallelism so that on my machine there are 2560 tasks (this is an old laptop with two cores and HT, so four actual execution threads), I get a lot of managers reporting they have 259 parsers available. Which points clearly to a problem registering parsers, in my case too many. Explains the lack of failure (I'm getting lucky and one of the parsers does the job) but the number of parsers should be 22 and be unchanging unless the classpath changes.

**Comment by ignazio1977** [comment]
The `typesCache` map has a list of values for each type; the list can be modified as new values are found, however in a multithreaded scenario one thread can get hold of a partially initialised list (i.e., one thread is still doing the initialisation work and the other threads find a non-empty list and assume the initialization is complete). this causes not enough parsers being found.

On the other hand, if more than one thread locks steps on this path, more than one thread will find the list empty and attempt to add elements to it, resulting in more parsers than necessary being registered.

The concurrent modification exception happens because the elements in the list are further processed in a stream; if the initialisation is ongoing on one thread while another thread has started processing the stream, new elements will be added to the list being streamed on, thus explaining the concurrent modification exception.

Solution: prepare the list and initialise it in one go, so that a) any thread accessing the list has either empty or fully populated list, nothing midway, and b) the list is functionally immutable, so no concurrent modification exceptions to be raised.

This does not address the double initialisation work, i.e., more than one thread might do the list initialisation work. However, this job is limited in size (one Class.forName for each type defined in service files) and this extra work only happens if managers are created all at once; if one manager is created /and then/ multiple threads try to get their own manager, all threads will find the collections already initialised. Synchronising the methods to avoid duplicate work is likely to be slower than allowing the occasional duplication, in common application scenarios.

**Comment by ignazio1977** [comment]
Workaround while the releases are prepared: create a manager before any multithreading access starts, this will do the initialisation job. I've tried this locally and can no longer reproduce the failure by adding 

            final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();

as first instruction in the main method.
