### ISSUE TITLE
OWLEntityRenamer and anonymous individuals

### ISSUE THREAD

**Issue by hammar** [owlcs/owlapi#892]
Hi,

I'm using the OSGI distribution of OWLAPI 4.5.9 in developing a Protégé 5.5.0 plugin.

I have come across what I think may be unexpected/unwanted behavior in the OWLEntityRenamer when renaming entities that have annotations with annotations on them. Since the generated identifiers for the intermediate annotations (anonymous individuals) are not maintained, the linkage between the first-order and second-order annotation is lost.

I attach a ZIP with a project that expresses this. On execution, this:

    <owl:Class rdf:about="http://karlhammar.com/owlapitest#Vehicle">
        <opla-sd:entityPosition>
            <rdf:Description>
                <opla-sd:entityPositionX rdf:datatype="http://www.w3.org/2001/XMLSchema#double">120.04594422899757</opla-sd:entityPositionX>
                <opla-sd:entityPositionY rdf:datatype="http://www.w3.org/2001/XMLSchema#double">89.51678985030932</opla-sd:entityPositionY>
                <rdfs:comment xml:lang="en">This is an entity positioning annotation generated by CoModIDE (https://comodide.com/). Removing this annotation will break rendering the CoModIDE schema diagram view.</rdfs:comment>
            </rdf:Description>
        </opla-sd:entityPosition>
    </owl:Class>

turns into this:

    <owl:Class rdf:about="http://karlhammar.com/owlapitest#Vehicle-renamed">
        <opla-sd:entityPosition>
            <rdf:Description/>
        </opla-sd:entityPosition>
    </owl:Class>
    <rdf:Description>
        <opla-sd:entityPositionX rdf:datatype="http://www.w3.org/2001/XMLSchema#double">120.04594422899757</opla-sd:entityPositionX>
        <opla-sd:entityPositionY rdf:datatype="http://www.w3.org/2001/XMLSchema#double">89.51678985030932</opla-sd:entityPositionY>
        <rdfs:comment xml:lang="en">This is an entity positioning annotation generated by CoModIDE (https://comodide.com/). Removing this annotation will break rendering the CoModIDE schema diagram view.</rdfs:comment>
    </rdf:Description>

Is this a bug, or am I just holding it wrong?

[OwlapiTest.zip](https://github.com/owlcs/owlapi/files/3780761/OwlapiTest.zip)

**Comment by hammar** [comment]
Apologies for the formatting of RDF/XML getting screwed up on paste.

**Comment by ignazio1977** [comment]
It looks like a bug to me. What's happening is that the annotations on the anonymous individual are separate axioms from main annotation axiom that, in XML, appears to wrap them.

When modifying IRIs, the axioms that get changed are the ones that have the IRI you wish to change in the signature - so the axioms that annotate the individual are not involved.

When modifying the axiom, the anonymous individual can be remapped or not - this is part of `OWLObjectDuplicator`. Remapping means that the anonymous individual is assigned a new id, so that old and new axiom become unrelated. The duplication is designed so that the same node is always remapped to the same new node, if a node appears in more than one axiom (as is the case here) or in more than one location in the object being duplicated.

However, here we have axioms where the node appears and which are not themselves modified, so the remapping effectively creates a new node and the existing axioms are left disconnected from the main annotation.

Workaround is to disable remapping: 

    AnonymousIndividualProperties.setRemapAllAnonymousIndividualsIds(false);

However this is a static setting and will affect any Protege save action where duplication of object happens, so it might have undesirable side effects.

**Comment by hammar** [comment]
Many thanks Ignazio; that workaround works as expected. We disable remapping just prior to executing the renaming, and reset it back to default afterwards; so it's a two-line fix. I'm very happy that this works, the other workaround I had in mind would have been substantially more complex (20+ LoC) and much uglier.
