### ISSUE TITLE
Builtin annotation properties lost during parsing

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#895]
The following testcase works well for v5.1.11, but fails for v5.1.12:

            String txt = "@prefix ex:    <http://ex.com#> .\n" +
                    "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n" +
                    "@prefix owl:   <http://www.w3.org/2002/07/owl#> .\n" +
                    "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n" +
                    "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n" +
                    "\n" +
                    "<http://ex.com#/ont>  a  owl:Ontology ;\n" +
                    "        ex:ap            \"x\" ;\n" +
                    "        owl:versionInfo  \"x\" .\n" +
                    "\n" +
                    "ex:ap   a       owl:AnnotationProperty .";
            OWLOntologyDocumentSource src = ReadWriteUtils.getStringDocumentSource(txt, OntFormat.TURTLE);
            OWLOntologyManager m = OntManagers.createOWL();
            OWLOntology o = m.loadOntologyFromOntologyDocument(src);
            Assert.assertEquals(2, o.annotationPropertiesInSignature().peek(System.out::println).count());

**Comment by ignazio1977** [comment]
Looks like a side effect of fixing #875. Builtin annotation properties, which do not need declarations, were treated as undeclared annotation properties and a guessed annotation property declaration was included. This let `versionInfo` make its way in the signature.

When the annotation property parsing was updated to recognize builtin properties as never needing a declaration, the guessed declaration was no longer created and the signature ignored the property use.

**Comment by ignazio1977** [comment]
Actually worse: if there are ontology annotations and one of them is not a builtin property, when the non builtin property is seen first the builtin property is dropped. Bad check on the set of pending annotations.

Builtin annotations are parsed in streaming mode, non builtin cannot be parsed the same way because a declaration must be seen beforehand - but the streaming mode has a bug that assumes the property just being parsed also exists as a pending annotation, or no pending annotations exist. That assumption is wrong and the fix is to add the currently parsed annotation regardless of whether there are pending annotations or not.
