### ISSUE TITLE
Inquiry on numeric literals

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#902]
I'm adding concrete domains in an EL++ ontology that currently uses classes to represent numbers.

For the OWL API, is there any upshot (memory footprint, etc.) to using xsd:integer over xsd:decimal when applicable?  

Example (considering the predicate declaration to have no range),

`DataHasValue(:hasStrengthValue "2"^^xsd:integer)`
over
`DataHasValue(:hasStrengthValue "2"^^xsd:decimal)`

**Comment by ignazio1977** [comment]
There is a specialised implementation fro integers but the difference is pretty small - an int instead of a String. I would expect this to make a measurable difference only if many thousands of instances were used, and the total memory consumption would still be dominated by axioms and indexing structures.

**Comment by rwynne** [comment]
@ignazio1977 Ahh, I see!  Right, it's measurable (this is a snomed-rxnorm mapping containing thousands of equivalencies). Even with partially implemented DataHasValue, Elk is still astonishingly fast.  I don't know what makes DataHasValue only partially implemented or potential barriers.  Now to try some DL queries with less-than/greater-than operands.
