### ISSUE TITLE
How to save ontologies **without** automatic entity declaration

### ISSUE THREAD

**Issue by ErgoSoftUK** [owlcs/owlapi#916]
Is it possible to create a reference such as...

`ObjectPropertyRange(ds:aeAttendanceSource sn:SN_999002991000000109)`

without the API automatically adding its declaration

`Declaration(Class(sn:SN_999002991000000109))`

I've tried : -

new OWLClassImpl(iri)
dataFactory.getOWLEntity(EntityType.CLASS, iri)
dataFactory.getOWLClass(iri)

and the all seem to generate a declaration (which further begs the question of whats the point in the dataFactory.getOWLDeclarationAxiom() method)?

Sample code (for the output, I dont want `Declaration(Class(<cm:Test2>))`):-

```java
public class Sandbox {
    @Test
    void autoDeclare() throws OWLOntologyCreationException, OWLOntologyStorageException {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology owlOntology = manager.createOntology();
        OWLDataFactory df = manager.getOWLDataFactory();

        // Not actually needed!?
        owlOntology.addAxiom(
            df.getOWLDeclarationAxiom(
                df.getOWLObjectProperty("cm:Test1")
            )
        );

        owlOntology.addAxiom(
            df.getOWLObjectPropertyRangeAxiom(
                df.getOWLObjectProperty("cm:Test1"),
                df.getOWLClass("cm:Test2")      // <--- HERE
            )
        );

         manager.saveOntology(
            owlOntology,
            new FunctionalSyntaxDocumentFormat(),
            System.out
        );
    }
}
```

**Comment by ignazio1977** [comment]
To skip adding missing type declarations, set this parameter on the format:

    OWLDocumentFormat format = new FunctionalSyntaxDocumentFormat();
    format.setAddMissingTypes(false);

before saving the ontology.

Since you mentioned declaration axioms, the factory allows creation first because it is used during parsing, and second because one might want to create an ontology containing only entity declarations, for example as part of a vocabulary.

Side note: a file without declarations and which does not import an ontology that declares the entities used is not a valid OWL ontology - all entities need at least one declaration in the imports closure.

Also, don't use the `-Impl` classes, they're not meant to be used directly. They're public only because there was no easy mechanism to make them available to factories and not visible to all users.

**Comment by matentzn** [comment]
This is so cool! I didnt know that!

**Comment by ErgoSoftUK** [comment]
@ignazio1977 Thanks, thats exactly what I was looking for.  And yes, I know the -Impl's shouldnt be used, I was just looking for a way to achieve my aims, even if temporarily.
