### ISSUE TITLE
OWLOntology#nestedClassExpressions() does not work with declarations

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#937]
Version 5.1.14.
The testcase:

            OWLOntologyManager m = OntManagers.createOWL();
            OWLDataFactory df = m.getOWLDataFactory();

            OWLOntology o = m.createOntology();
            o.add(df.getOWLDeclarationAxiom(df.getOWLClass("a")));
            o.add(df.getOWLDeclarationAxiom(df.getOWLClass("b")));
            o.add(df.getOWLDeclarationAxiom(df.getOWLClass("c")));
            o.add(df.getOWLSubClassOfAxiom(df.getOWLClass("a"), df.getOWLClass("b")));

            Assert.assertEquals(3, o.nestedClassExpressions().peek(System.out::println).count());

This seems to be correct behavior which is by design.
But, in that case, it would be nice to have few words in javadocs.
This is not entirely clear - initially I expected that the declarations would also be considered.

PS - my work is a bit dependent on this issue, so it would be nice if this was taken as a question in the first place.

**Comment by ignazio1977** [comment]
Method name and javadoc suggest to me that only anonymous OWLClassExpressions, and not OWLClasses, should be included. However the implementation includes logical axioms (thus excluding OWLClass instances) but includes all expressions that can contain anonymous and named classes, and explicitly includes any OWLClass that appears, for example, as part of an intersection.

Not enough uses in code I can see to ascertain which was intended. I assume applications are using the signature as well as the nested class expressions, where needed. I believe it's safest to document the behaviour rather than change it.
