### ISSUE TITLE
Augment 'Deprecated use the stream method' Javadoc across codebase

### ISSUE THREAD

**Issue by lewismc** [owlcs/owlapi#950]
Hi folks, using the Java API today I noticed that the [OWLOntology Javadoc](http://owlcs.github.io/owlapi/apidocs_5/index.html?org/semanticweb/owlapi/model/OWLOntology.html) is not intuitive whenever it uses 
```
Deprecated. 
use the stream method
```
There are 14 occurrences in this one file which I want to fix.
I found the following SO thead which talks about this issue as well. [how to get all the classes defined in an ontology, using owlapi in a none deprecated way](https://stackoverflow.com/questions/42984384/how-to-get-all-the-classes-defined-in-an-ontology-using-owlapi-in-a-none-deprec).

I'll go ahead and file a PR shortly

**Comment by Cydny** [comment]
Hi,

I 100% agree.

The way streams are introduced in version 5 of the OWL API  is not only 'not intuitive' but in fact incorrect.
Streams do not 'replace' sets or make them redundant (thinking of streams as the 'modern way' as suggested by the SO thread is also incorrect).
They are conceptually different and are used for different purposes.
There is a reason why Streams do not implement the 'Collection' interface.
It even explicitly says so in the documentation for streams: "Collections and streams, while bearing some superficial similarities, have different goals."

We need proper support for both streams and sets.

**Comment by ignazio1977** [comment]
> The way streams are introduced in version 5 of the OWL API is not only 'not intuitive' but in fact incorrect.

The purpose is misunderstood. The streams were not introduced to replace the collections, they were introduced to replace **the most common use of the sets returned by those methods**.

That use being, iteration and possibly transformation of the elements in the sets. these are overwhelmingly more common than other uses where sets are better than streams - namely, checking if elements exist.

All the sets in question are labeled as copies of the underlying collections - which turned out to be very expensive, there's a long story of optimizations and attempted optimizations to work around the cost of making these copies only to iterate over them or to check containments.

You **have** support for streams and sets. Even after removing the deprecated methods, conveniences for turning a stream into a set are available.

**Comment by Cydny** [comment]
Hi,

thanks for the quick reply!

I am not convinced by the argument.
Even if the OWL API is commonly used for purposes where streams are most suitable, this does not mean that it's a good idea to make the API somewhat inconvenient or counter-intuitive to use for other purposes.

**Comment by ignazio1977** [comment]
Counterintuitive is often a matter of opinion.

As for inconvenient, why?

The methods have not been removed in version 5. They have in version 6, and there will be adapters so that developers can choose to continue working with older API versions while they choose how to evolve their applications. And in the years since version 5 first release only the documentation has been found lacking.

**Comment by Cydny** [comment]
This seems to suggest that the OWL API will move forward only using streams where there is no equivalent for sets in older versions? Will there be adapters for these new features as well? If not, then I will need to write my own adapters. That is inconvenient.

**Comment by ignazio1977** [comment]
When new features are introduced, the code is there for people to peruse. It's easy to ask for features to be included in previous versions or in adapters.

That said, aren't you worrying prematurely? You're afraid you'll have to write adapters for functionality that does not exist yet because sets might be more convenient than streams to use these new functionalities.

**Comment by ignazio1977** [comment]
Looking at the stack overflow question, there's a much shorter to type answer (not sure why an OWLClass[] array was used at all...)

`OWLAPIStreamUtils.asSet(Stream)` is what the existing deprecated methods call under the cover.

**Comment by sszuev** [comment]
Hello everyone.
There is one more opinion.
OWL API(-api) is an API which could be implemented in different ways.
Different data structures could underlay the main interface. 
In terms of performance, sometimes stream-based methods could be preferable (for example when there is a RDF Graph with unknown nature), but sometimes collection-based ones (when the underlying data is really collections-made).
So I think both ways must be present in API, and marking one of the method families as deprecated maybe not fully correct.

**Comment by Cydny** [comment]
> That said, aren't you worrying prematurely? 

There are already a few instances w.r.t. streams and collections in the OWL API 5 where I stumbled across features that made me scratch my head.
For example, the interface http://owlcs.github.io/owlapi/apidocs_5/org/semanticweb/owlapi/model/HasOperands.html
only specifies functions for a stream and a list.
So, say for a OWLEquivalentClassesAxiom, I can get its operands as a stream or list.
To me, this is counter-intuitive because the OWL language specification uses sets rather than lists.

Is it a big deal? No. I can easily convert a stream or a list to a set. But this is an extra function call and that is arguably inconvenient. But most importantly, it makes me wonder whether I am using the OWL API incorrectly or whether I am misunderstanding something.

> So I think both ways must be present in API, and marking one of the method families as deprecated maybe not fully correct.

This is exactly right.

**Comment by lewismc** [comment]
I'm going to go ahead and close this issue folks. It seems like opening another issue to address the following may be the next step...

> So I think both ways must be present in API, and marking one of the method families as deprecated maybe not fully correct.
