### ISSUE TITLE
Sets or streams?

### ISSUE THREAD

**Issue by ignazio1977** [owlcs/owlapi#958]
Hello everyone.
There is one more opinion.
OWL API(-api) is an API which could be implemented in different ways.
Different data structures could underlay the main interface. 
In terms of performance, sometimes stream-based methods could be preferable (for example when there is a RDF Graph with unknown nature), but sometimes collection-based ones (when the underlying data is really collections-made).
So I think both ways must be present in API, and marking one of the method families as deprecated maybe not fully correct.

_Originally posted by @sszuev in https://github.com/owlcs/owlapi/issues/950#issuecomment-660485828_

**Comment by ignazio1977** [comment]
Just so I'm clear, are we proposing removing the deprecation annotation from the set methods which have an equivalent stream method?

**Comment by Cydny** [comment]
I suggest to provide set methods everywhere where the structural specification for OWL (https://www.w3.org/TR/owl2-syntax/) specifies elements of the language with sets. I would also suggest to make it clear in the documentation whether these sets are copies or references and hint at (some) potential risk for using sets.

**Comment by ignazio1977** [comment]
So no change then.

**Comment by Cydny** [comment]
The interface http://owlcs.github.io/owlapi/apidocs_5/org/semanticweb/owlapi/model/HasOperands
currently only provides lists and streams.
So for any OWL constructor using this interface, there is currently no equivalent for sets.
Example:
Consider http://owlcs.github.io/owlapi/apidocs_5/org/semanticweb/owlapi/model/OWLEquivalentClassesAxiom.html.
The specification for OWL defines the arguments for this type of axiom as a set: https://www.w3.org/TR/owl2-syntax/#Equivalent_Classes.
However, there is no method that provides a set for the operands of  an OWLEquivalentClassesAxiom in the OWL API.
Only methods that return either a stream or a list.

**Comment by Cydny** [comment]
> So no changes then

Removing the deprecation annotations is still an important first step.
The set methods are not 'deprecated'.

**Comment by sszuev** [comment]
> The interface http://owlcs.github.io/owlapi/apidocs_5/org/semanticweb/owlapi/model/HasOperands
> currently only provides lists and streams.



1) just to clarify,
my proposition (and this issue I believe) is about removing `@Deprecated` annotations only, 
not about adding new functionality. 
If you want to add into `HasOperand` a method returning `Set`, I think, it is better to start a new issue.
I think, old methods have been working good, and marking them as `@Deprecated` means forcing clients to use `.collect(Collectors.toXXX)` construction, which may be inafficient if the underlying data is already in the same form as it is required, which is usually true.  And, honestly, I just don't see a good reason why it was done.

2) Actually, I can't find anything about `Set`s in the specification (the provided link). 
But, obviously, there is no much sense in the axiom `<a:a> owl:equivalentClass <a:a>`.
So, the underlying data could be `Set`-based, but it is actually `List`-based (at least in OWL-API-impl, v 5.1.14). 
Why? 
Maybe because RDF allows it. 
Or maybe because `List` is more generic then `Set` (you can turn a list into a set, but cannot do the opposite without losing info). Or maybe because a lot of tools and APIs can produce such axioms. Or because of historical reasons. Or maybe because OWL could really accept such duplicates in some strange semantics, and to decide if this correct or not there are reasoners; the purpose of API is not to judge such situations, but to provide correctness in the base sense.
At least, for some constructions (e.g. for `ObjectPropertyChain( OPE1 ... OPEn )`) duplicates are allowed.

Shortly speaking, I am not sure that it is a good idea to add into `HasOperand` a method returning `Set`
(it seems to me it is nothing but syntactic sugar , but on the other hand I don't think it would be bad).
But I am sure, removing `@Deprecated` tag for `HasSignature#getSignature()` would be better than removing that method as deprecated.

**Comment by Cydny** [comment]
> Actually, I can't find anything about Sets in the specification (the provided link).

It says "By default, all associations are sets; that is, the elements in them are unordered and repetitions are disallowed." in the structural specification for OWL in Section "2 Preliminary Definitions" in [https://www.w3.org/TR/owl2-syntax/](https://www.w3.org/TR/owl2-syntax/).

OWL is definitely defined in terms of sets and not lists.
Which is why I suggest that the OWL API supports the (normative) specification for OWL.

Set semantics have some rather serious implications. For example, a tautology such as `OWLEquivalentClasses(A,A)` is strictly speaking not an OWL axiom. Due to OWL's set semantics, this would be the same as `OWLEquivalentClasses(A)`.
But this does not conform to the specification, since its [definition](https://www.w3.org/TR/owl-syntax/#Equivalent_Classes
) requires at least two (different) class expressions.
However, `OWLSubClassOf(A,A)` is an OWL axiom, because the arguments for `OWLSubClassOf` are not specified as a set.
Still, there are practical reasons of why one would like to express such tautologies.
This topic has already been discussed before: see [#776](https://github.com/owlcs/owlapi/issues/776)

**Comment by sszuev** [comment]
> It says "By default, all associations are sets; that is, the elements in them are unordered and repetitions are disallowed." in the structural specification for OWL in Section "2 Preliminary Definitions" in https://www.w3.org/TR/owl2-syntax/.

Well, I see.
But still not sure about reasonableness of adding a new common method into that generic interface (`HasOperands`). 
There is already (but deprecated) `OWLNaryClassAxiom#getClassExpressions()`, it must be enough.  It is accessible from `OWLEquivalentClassesAxiom`, of course. And the underlying data (OWL-API-impl) is also distinct (although it is in the form of list, not set).

**Comment by Cydny** [comment]
> There is already (but deprecated)` OWLNaryClassAxiom#getClassExpressions()`, it must be enough.

That is the question. Is it enough?

To my understanding, the OWL API is primarily concerned with OWL.
And if OWL - as a logical language - defines its elements via sets, then there should be a very strong argument for **not** providing functions that reflect these set semantics. And I don't see this argument. (The OWL API can very well be maintained via streams under to hood. But this is an implementation detail that should not be confused with OWL's specification.)

Also, keep in mind that this is not to say that the OWL API should not provide other features besides methods for sets.
Quite the contrary! Many programs and tools are built using the OWL API. And these tools often work with say, lists or streams.
So it is very sensible for the OWL API to provide these alongside methods for sets.

**Comment by sszuev** [comment]
In programming there is KISS principle (that is a kind of rephrasing of Occam's razor). 
So I vote against adding new methods. 

Especially considering that all functions are already there. All functions to work with sets.
It is not so easy to find them, but this is a consequence of historical traditions and the ease of adding new functionality - at some point in time it became too many methods and interfaces. 
Maybe it would be better to have single `HasOperands#getOperandsAsSet()` instead of `OWLNaryClassAxiom#getClassExpressions()`,  `OWLNaryIndividualAxiom#getIndividuals()` and others. 
But people would complain that they can't find an appropriate method, if there were no hints in method's names. 
And it seems to be another question.
So now, I am sure, there is no need to add a new method.

Another thing - the existing deprecated `Set`-based methods: they are already there, and they are in use, people know them. 
And sometimes these methods could be more preferable than stream-based companions.
Removing `@Deprecated` annotation is easy and safe, no side effects.
But adding new functionality can be dangerous, new method of such kind would only complicate the picture.

**Comment by Cydny** [comment]
In Software Engineering, one usually implements a system according to a specification.

Not following the specification, which in this case specifies sets, will lead to confusion.

But these are just my 2 cents.

**Comment by lewismc** [comment]
Hi folks. My input here is that until about 3 days ago I had not looked at the OWLAPI Java source in a few years. You guys have quite clearly implement an extremely comprehensive and utterly verbose Java OWL API. Its both amazing and pretty daunting at the same time. Totally developer orientated. 
It was pretty unclear to me what I should be using, when and where. 
I used the mailing list and a HUGE thank you to @ignazio1977 for the assistance. 
RE: Sets or/vs Streams I would literally remove the deprecation's unless there is a compilation and/or runtime performance benefit. 
The **utility** feature is quite clearly under scrutiny.
Again, hats off from me for implement an extremely comprehensive API... it's just a bit overwhelming at times for re-new-bees-like-me :)

**Comment by ignazio1977** [comment]
As for unordered collections without repetitions in the OWL 2 specs, two things:
- `without repetitions` caught at least one of the authors of the specs by surprise a few years after they were completed
- `unordered` does not mean adding an order to the collections is forbidden; it means the order has no logical effect
- a List without repetitions differs from a set in no way except performance of various operations. No semantic difference, a number of practical advantages, e.g., the same ontology gets serialized the same way, and modifications have local impact on the serialization, which is a very important feature for those who store ontologies in git repositories and similar.
- not following the specification would happen if duplicates were not removed. The specs do not mandate java.util.Set; only behaviour equivalent to that of sets is required.
- 'sometimes sets are better', and those sometimes are fewer than the times they're just an extra cost. Couple that with the expectation, derived from earlier implementation choices, that the returned sets be defensive copies of the data, and that's a performance sink I've met multiple times.

As for basic software engineering principles, let us not patronise each other restating the obvious.

Conclusion: you want the deprecations removed. Good, that means at long last enough people are using version 5 to have noticed which parts they don't like.
