### ISSUE TITLE
Error with undeclared classes in domain axioms

### ISSUE THREAD

**Issue by violarodrigues-dataworld** [owlcs/owlapi#962]
Tried version:  5.1.6 and higher

On loading turtle document containing the lines below
```
@prefix test: <http://www.example.com/test#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

test:not_supported_1 a owl:DatatypeProperty ;
                   rdfs:domain test:Case_0_Domain_0 ,
                               [ rdf:type owl:Class ;
                                 owl:unionOf ( test:Case_2_Domain_0
                                               test:Case_2_Domain_1
                                               test:Case_2_Domain_2
                                             )
                               ]  .
```
I get this error message
org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://www.w3.org/2002/07/owl#unionOf -> _:genid-nodeid-node1egfqhmh6x1 -> _:genid-nodeid-node1egfqhmh6x2

Jena can read this document without any error.

**Comment by ignazio1977** [comment]
That's not an error, it's a warning. It's outputted only if the log level is set to debug or finer than that.

The unparsed triples messages are not 100% reliable (haven't managed to track down why).

In this case, it thinks the triples that are part of the list haven't been all used during parsing; however, the axiom parsed is correct.

    Ontology(OntologyID(Anonymous-2)) [Axioms: 3 Logical Axioms: 2] 
        {Declaration(DataProperty(<http://www.example.com/test#not_supported_1>))
        DataPropertyDomain(<http://www.example.com/test#not_supported_1> <http://www.example.com/test#Case_0_Domain_0>) 
       DataPropertyDomain(<http://www.example.com/test#not_supported_1> ObjectUnionOf(
              <http://www.example.com/test#Case_2_Domain_0> 
              <http://www.example.com/test#Case_2_Domain_1> 
              <http://www.example.com/test#Case_2_Domain_2>)) 
       }

**Comment by violarodrigues-dataworld** [comment]
Its surprising that it parsed the example turtle doc without any issues. It worked for me as well. The example I copied was a part of the bigger turtle document and I did not test that example before sharing here. 

Can you please check with this one? 
```
@prefix test: <http://www.example.com/test#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

test:not_supported_1 a owl:DatatypeProperty ;
                   rdfs:domain test:Case_0_Domain_0 ,
                               [ rdf:type owl:Class ;
                                 owl:unionOf ( test:Case_2_Domain_0
                                               test:Case_2_Domain_1
                                               test:Case_2_Domain_2
                                             )
                               ]  ;
                     rdfs:range  xsd:long .

```

This document does not get parsed correctly
`Ontology(OntologyID(Anonymous-2)) [Axioms: 4 Logical Axioms: 3] First 20 axioms: {
DataPropertyRange(<http://www.example.com/test#not_supported_1> xsd:long) 
DataPropertyDomain(<http://www.example.com/test#not_supported_1> <http://www.example.com/test#Case_0_Domain_0>) 
DataPropertyDomain(<http://www.example.com/test#not_supported_1> <_:genid-nodeid-node1egi4nnfjx1>) 
Declaration(DataProperty(<http://www.example.com/test#not_supported_1>)) }`

**Comment by ignazio1977** [comment]
Interesting problem, the log shows the following in the second example:

2020-10-03 19:44:38:418 +0100 [main] WARN org.semanticweb.owlapi6.utility.OWLAnnotationPropertyTransformer - Annotation property domain axiom turned to data property domain after parsing. This could introduce errors if the original domain was an anonymous expression: http://www.example.com/test#Case_0_Domain_0 is the new domain.
2020-10-03 19:44:38:427 +0100 [main] WARN org.semanticweb.owlapi6.utility.OWLAnnotationPropertyTransformer - Annotation property domain axiom turned to data property domain after parsing. This could introduce errors if the original domain was an anonymous expression: _:genid-nodeid-node1ejnsfdqcx1 is the new domain.

It's triggered by the presence of a range axiom; it appears the range axiom is parsed before the declaration axiom, because when the domain is parsed `test:not_supported_1` is typed as an annotation property, which it shouldn't have.

**Comment by ignazio1977** [comment]
Debugged this, the statements are parsed in the expected order, the issue here is that checking for domain axioms is strict without options to relax if violations like undeclared classes exist in the input. In this case, `test:Case_0_Domain_0` is not declared as a class and causes the property to be typed as annotation property (it is a guess, but a better guess would be to assume `test:Case_0_Domain_0` is a class.

With declarations (i.e., with no OWL 2 violations) the file parses correctly, and the nested anonymous expressions seem to not play a part one way or another.

Without declarations, I can put a patch in, but this really needs to be sorted as part of existing redesign plans to make strict/lax parsing more uniform and controllable.
