### ISSUE TITLE
How do I ensure an exact roundtrip for a property of type InverseFunctionalProperty

### ISSUE THREAD

**Issue by violarodrigues-dataworld** [owlcs/owlapi#963]
Hi,

A raw rdf file containing an entity declared as 
`foaf:yahooChatID a rdf:Property,owl:DatatypeProperty, owl:InverseFunctionalProperty;`
when goes through owlApi, it explicitly adds owl:ObjectProperty on this entity.

When this new owlApi parsed document is used to regenerate raw rdf, I get
`foaf:yahooChatID        a    owl:DatatypeProperty , owl:InverseFunctionalProperty , owl:ObjectProperty ; `

How do I ensure that `owl:ObjectProperty` is not explicitly mentioned on this entity?

**Comment by ignazio1977** [comment]
This is not as easy as it seems. It is possible to tell a format renderer to not add implicit types and only output explicit declarations, which allows you to create an output file without an object property declaration for this scenario.

E.g., like this:

        OWLDataFactory df = OWLManager.getOWLDataFactory();
        OWLOntology o = OWLManager.createOWLOntologyManager().createOntology();
        IRI iri = IRI.create("urn:testdataproperty");
        o.getOWLOntologyManager().addAxiom(o,
            df.getOWLInverseFunctionalObjectPropertyAxiom(df.getOWLObjectProperty(iri)));
        o.getOWLOntologyManager().addAxiom(o,
            df.getOWLDeclarationAxiom(df.getOWLDataProperty(iri)));
        OWLDocumentFormat f = new RDFXMLDocumentFormat();
        f.setAddMissingTypes(false);
        o.saveOntology(f, System.out);


However the problem here is that `owl:InverseFunctionalProperty` can only be applied to object properties, according to the OWL 2 mapping to RDF, and if a parser sees `rdf:Property` together with either data or object property declarations, it is supposed to ignore it - so, roundtripping the `rdf:Property` bit is difficult. Similarly, in the same OWL 2 mapping spec, if a property is of type `InverseFunctionalProperty`, an object property declaration should be added. So, regardless of the settings on the output, an OWL 2 conformant parser would parse the input and put in the ontology the declarations you don't want to see.

I haven't tried to see if in your case the problem is the output settings or the input parsing. Try tweaking the output format as shown above, but if it doesn't help then I don't think we can do much; we cannot change OWLAPI to be less conformant on this facet, because it would likely cause it to misbehave on ontologies that are relying on those mapping features.

**Comment by violarodrigues-dataworld** [comment]
I tried tweaking the output, but it didn't help. It is most likely the input parsing.
```

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xml: <http://www.w3.org/XML/1998/namespace>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.


foaf:yahooChatID a rdf:Property,
                   owl:DatatypeProperty,
                   owl:InverseFunctionalProperty;
                 rdfs:comment "A Yahoo chat ID";
                 rdfs:label "Yahoo chat ID".
```
For the document above, the axioms parsed look like this
```

[Axioms: 5 Logical Axioms: 1] First 20 axioms: {Declaration(DataProperty(<http://xmlns.com/foaf/0.1/yahooChatID>)) 
Declaration(ObjectProperty(<http://xmlns.com/foaf/0.1/yahooChatID>)) 
AnnotationAssertion(rdfs:comment <http://xmlns.com/foaf/0.1/yahooChatID> "A Yahoo chat ID"^^xsd:string) 
AnnotationAssertion(rdfs:label <http://xmlns.com/foaf/0.1/yahooChatID> "Yahoo chat ID"^^xsd:string) 
InverseFunctionalObjectProperty(<http://xmlns.com/foaf/0.1/yahooChatID>) }
```
