### ISSUE TITLE
OWLLiteral for XSD:Long

### ISSUE THREAD

**Issue by Galigator** [owlcs/owlapi#970]
How can we create an OWLLiteral that contain a long with type XSDVocabulary.LONG. 'long' is not only a native type for java but also a very used type even for non-low level task.

My typical usage would be to encode the return of System.currentTimeMillis() into an ontology.
But many time operations, computations, can be store into an 'int'.

Right now I am encoding my 'long's  as Strings but it is painful when time come to give the ontology to someone else and explain him that "I am using String instead of Long because the lib I use don't provide me helpers to do it easily...", and then he reply "so we can't do real math computation in SWRL over String"...

How can I a provide my own OWLLiteral to owlapi ? long is sure nice, bug long[] or even long[][] ... Tensor<Long> would be definitely awesome.

Still admiring quality of owlapi.

**Comment by ignazio1977** [comment]
Looks like the convenience method for Long got missed.

You can create them with

    owlDataFactory.getOWLLiteral(Long.toString(longValue), OWL2Datatype.XSD_LONG);

To parse it back to a long value would be a matter of using Long.parseLong on the literal string:

    long longValue=Long.parseLong(literalObject.getLiteral());

These literals would be relatively memory expensive (other literals containing primitive types, e.g., int, boolean, float, double, do not keep the string literal in memory, nor the datatype pointer, but there is no special type for longs).

Adding your own implementation for other types would be simple enough to do but might be complex to release. It would carry some interface changes, so it might be difficult to package for use by a third party as an OWLAPI add on, so basically you'd have to maintain your own fork.

There's nothing currently in the interface for parametrizing OWLLiteral (i.e., OWLLIteral<long[]>), and to do so would be quite far reaching. Maybe some default method on OWLLiteral might be enough?

    public <T> contentAs(Function<OWLLiteral, T> f)

then you could easily provide a function for turning a standard literal into long[], or indeed any other convenience type.

An equivalent method on OWLDataFactory might allow the caller to inject code to select which OLLiteral implementation to use, in order to provide efficient memory management for specific types; it wouldn't tie you in knots to surface yet another set of type specific convenience methods.

One complication would be that storage to file still needs to write out the data as a string - that's all that RDF mapping will support, for example. Also, if you choose to use your own datatype IRI (I'm not aware of a datatype for arrays, so I think that would be necessary), various tools might raise issues complaining of unsupported datatypes (so your mileage may vary).

As for plain longs, adding them as a special case (and maybe doing the same for other primitive types) is probably common enough to warrant its own enhancement.

**Comment by Galigator** [comment]
Thank you for theses details.
As I understand a PR for an OWLLiteral "long" could be accept.
Right now I am using Long.toString(longValue, 36) to compress a bit more long values.

For other type, it is true that storage is always a problem, right now I am not using owlapi tools for that but a custom mapper to virtuoso (graph / logic / etc..) and lucene-rawfile(long[][] / images / tensors / etc... ).
